'use strict';
let courseSession = null;
const courseGroup = unit => COURSE_LESSONS.filter(t=>t.unit===unit);
const courseName = unit => unit==='foundations'?'Foundations':'Unit 1 · One-variable statistics';
function courseOverview(unit) {
 const topics=courseGroup(unit);
 main.innerHTML=`<a class="text-link" href="#course">← All units</a><p class="eyebrow">${unit==='foundations'?'START HERE':'UNIT 1'}</p><h1 class="page-title">${esc(courseName(unit))}</h1><p class="intro">Learn one skill at a time. Read the examples, work on paper, then practice independently.</p><div class="controls"><a class="button" href="#study/${topics[0].id}">Start learning</a><a class="button light" href="#unitpractice/${unit}">Mixed practice</a><a class="button light" href="#unitcheck/${unit}">Unit self-check</a></div><p class="muted">${topics.length} lessons · ${topics.length*4} worked examples · ${topics.length*20} practice questions</p><div class="u2-grid">${topics.map((t,i)=>{const a=progress.attempts.filter(a=>a.courseUnit===unit&&a.skill===t.id);return `<article class="card skill-card"><p class="eyebrow">LESSON ${i+1}</p><h3>${esc(t.title)}</h3><p>${esc(t.summary)}</p><p class="muted">4 worked examples · 20 practice questions</p>${a.length?`<p>${a.filter(x=>x.correct&&!x.assisted).length}/${a.length} independent first-try answers</p>`:''}<div class="controls"><a class="button" href="#study/${t.id}">Study examples</a><a class="button light" href="#skillpractice/${t.id}">Practice</a></div></article>`;}).join('')}</div><section class="card study-routine"><h2>A simple study routine</h2><p>Read the idea, study two examples, then cover the solutions and try them yourself. Complete a short practice session. Use the self-check after you have studied every skill.</p><a class="text-link" href="#unit/${unit==='foundations'?'statistics':'equations'}">Next: ${unit==='foundations'?'Unit 1 · One-variable statistics':'Unit 2 · Equations & systems'} →</a></section>`;
}
function courseStudy(id) {
 const t=COURSE_LESSONS.find(t=>t.id===id);if(!t)return course();
 progress.lessonStarted=true;progress.courseLast=id;progress.lastLessonRoute=`#study/${id}`;save();
 const group=courseGroup(t.unit), next=group[group.indexOf(t)+1];
 main.innerHTML=`<a class="text-link" href="#unit/${t.unit}">← ${esc(courseName(t.unit))}</a><h1 class="page-title">${esc(t.title)}</h1><p class="intro">${esc(t.summary)}</p><div class="lesson-tabs"><a href="#" data-scroll="course-understand">Understand</a><a href="#" data-scroll="course-examples">4 worked examples</a><a href="#" data-scroll="course-try">Try one</a><a class="button" href="#skillpractice/${id}">Practice this skill</a></div><section class="card" id="course-understand"><h2>Understand the idea</h2>${t.ideas.map(p=>`<p>${esc(p)}</p>`).join('')}<div class="method-box"><h3>Your method</h3><ol>${t.method.map(p=>`<li>${esc(p)}</li>`).join('')}</ol></div><p class="hint"><strong>Common mistake:</strong> ${esc(t.mistake)}</p></section>${id==='signed-numbers'?courseNumberTool():t.unit==='statistics'?courseDataTool():''}<section id="course-examples"><div class="section-heading"><div><h2>Four worked examples</h2><p>Every step is visible. Cover the solution and explain the method in your own words.</p></div><button class="ghost" id="course-toggle">Hide all solutions</button></div><div class="worked-grid">${COURSE_BANK[id].slice(0,4).map((q,i)=>`<article class="card worked-example"><p class="eyebrow">EXAMPLE ${i+1}</p><h3>${esc(q.prompt)}</h3><details open><summary>Step-by-step solution</summary>${u2Steps(q)}</details></article>`).join('')}</div></section><section class="card" id="course-try"><h2>Now try one yourself</h2><p>Write your steps on paper. This guided question does not affect your independent-practice score.</p><div id="course-guided"></div></section><section class="card study-routine"><h2>For studying together</h2><p>${esc(t.parent)}</p><p>Ask: “Why does that step work?” and “How could you check your result?”</p></section><section class="card study-routine"><h2>Ready for more?</h2><div class="controls"><a class="button" href="#skillpractice/${id}">Practice this skill</a>${next?`<a class="text-link" href="#study/${next.id}">Next: ${esc(next.title)} →</a>`:`<a class="text-link" href="#unitcheck/${t.unit}">Try the unit self-check →</a>`}</div></section>`;
 document.querySelectorAll('[data-scroll]').forEach(a=>a.onclick=e=>{e.preventDefault();document.getElementById(a.dataset.scroll).scrollIntoView({behavior:'smooth'});});
 document.getElementById('course-toggle').onclick=e=>{const open=e.target.textContent.startsWith('Show');document.querySelectorAll('.worked-example details').forEach(d=>d.open=open);e.target.textContent=open?'Hide all solutions':'Show all solutions';};
 u2QuestionUI(COURSE_BANK[id][4],document.getElementById('course-guided'),null);
 if(id==='signed-numbers')courseWireNumber();if(t.unit==='statistics')courseWireData();
}
function coursePractice(id, check=false) {
 const t=COURSE_LESSONS.find(t=>t.id===id),unit=t?t.unit:id,topics=courseGroup(unit);if(!topics.length)return course();
 courseSession=null;
 main.innerHTML=`<a class="text-link" href="#unit/${unit}">← ${esc(courseName(unit))}</a><h1 class="page-title">${esc(t?t.title:courseName(unit))} ${check?'self-check':'practice'}</h1><p class="intro">${check?`${topics.length*2} questions: two per skill. Work independently; answers and explanations appear at the end.`:'Work on paper, enter your answer, and check. Use a hint when you need one.'}</p><section class="card"><div class="controls">${check?'':`<label>Session length <select id="course-count"><option value="5">5 questions</option><option value="10" selected>10 questions</option><option value="20">20 questions</option></select></label>`}<button class="primary" id="course-start">${check?'Start self-check':'Start practice'}</button>${t?`<a class="text-link" href="#study/${id}">Study examples first</a>`:''}</div><p class="muted">${t?'20 questions in this skill’s practice bank.':`Questions rotate across ${topics.length} skills. Choose at least ${topics.length} questions to include every skill.`}</p></section><div id="course-session"></div>`;
 document.getElementById('course-start').onclick=()=>{
  const count=check?topics.length*2:Number(document.getElementById('course-count').value);
  const groups=shuffle(t?[t]:topics).map(t=>shuffle(COURSE_BANK[t.id].slice(4)));
  const questions=Array.from({length:count},(_,i)=>groups[i%groups.length][Math.floor(i/groups.length)]);
  courseSession={unit,questions,index:0,results:[],check};document.getElementById('course-start').disabled=true;courseQuestion();
 };
}
function courseQuestion(){
 const s=courseSession,el=document.getElementById('course-session');
 if(s.index===s.questions.length){
  const correct=s.results.filter(a=>a.correct&&!a.assisted).length;
  el.innerHTML=`<section class="card question-card"><p class="eyebrow">SESSION COMPLETE</p><h2>${correct} of ${s.results.length} independent correct answers</h2><p>Review any skill that needed help, then try it again another day. A single session does not prove mastery.</p>${[...new Set(s.results.map(r=>r.skill))].map(id=>{const a=s.results.filter(r=>r.skill===id),t=COURSE_LESSONS.find(t=>t.id===id);return `<p><strong>${esc(t.title)}:</strong> ${a.filter(r=>r.correct&&!r.assisted).length}/${a.length} <a class="text-link" href="#study/${id}">Review examples →</a></p>`;}).join('')}<div class="controls"><a class="button" href="#unit/${s.unit}">Back to unit</a><a class="button light" href="#review">Review mistakes</a></div><h3>Answers and explanations</h3>${s.results.map((r,i)=>`<details><summary>${i+1}. ${esc(r.question.prompt)} — ${r.correct&&!r.assisted?'Correct independently':'Review'}</summary>${u2Steps(r.question)}</details>`).join('')}</section>`;return;
 }
 const q=s.questions[s.index];el.innerHTML=`<section class="card question-card"><p class="eyebrow">QUESTION ${s.index+1} OF ${s.questions.length} · ${esc(q.title)}</p><div id="course-question"></div></section>`;
 u2QuestionUI(q,document.getElementById('course-question'),r=>{s.results.push(r);s.index++;courseQuestion();},s.check);
 el.scrollIntoView({block:'start',behavior:'smooth'});
}
function coursePracticeHub(){
 main.innerHTML=`<h1 class="page-title">Choose what to practice</h1><p class="intro">Choose a unit for mixed questions, or open its study center to practice one skill.</p><div class="u2-grid">${['foundations','statistics','equations'].map(unit=>`<section class="card"><h2>${esc(unit==='equations'?'Unit 2 · Equations & systems':courseName(unit))}</h2><div class="controls"><a class="button" href="${unit==='equations'?'#u2practice/all':'#unitpractice/'+unit}">Mixed practice</a><a class="button light" href="#unit/${unit}">Choose a skill</a></div></section>`).join('')}</div><p class="notice">Detailed lessons for Units 3–7 are the next course expansion. Their existing introductory questions are also available.</p><a class="text-link" href="#practice/mixed">Other introductory practice →</a>`;
}
function courseNumberTool(){return `<section class="card study-routine"><h2>Explore the number line</h2><p>Choose a starting value and an amount to add. A negative amount moves left.</p><div class="controls"><label>Start <input id="number-start" type="range" min="-8" max="8" value="-3"></label><label>Add <input id="number-add" type="range" min="-8" max="8" value="5"></label></div><p id="number-caption" role="status"></p><svg id="number-line" viewBox="0 0 640 110" role="img" aria-label="Number line showing a starting point and result" style="width:100%;max-width:640px"></svg></section>`;}
function courseWireNumber(){const draw=()=>{const a=+document.getElementById('number-start').value,b=+document.getElementById('number-add').value,x=n=>320+n*17;document.getElementById('number-caption').textContent=`${a} + (${b}) = ${a+b}. Move ${Math.abs(b)} places ${b<0?'left':'right'}.`;document.getElementById('number-line').innerHTML=`<path d="M30 64H610" stroke="#536875"/>${Array.from({length:17},(_,i)=>{const n=i*2-16;return `<path d="M${x(n)} 60v8" stroke="#536875"/><text x="${x(n)}" y="89" text-anchor="middle" font-size="12">${n}</text>`;}).join('')}<path d="M${x(a)} 55V32H${x(a+b)}V55" fill="none" stroke="#24696b" stroke-width="3"/><circle cx="${x(a)}" cy="64" r="5" fill="#bc7d3d"/><circle cx="${x(a+b)}" cy="64" r="6" fill="#24696b"/><text x="${x(a+b)}" y="20" text-anchor="middle" font-size="14">${a+b}</text>`;};document.getElementById('number-start').oninput=draw;document.getElementById('number-add').oninput=draw;draw();}
function courseDataTool(){return `<section class="card study-routine"><h2>Explore a data set</h2><p>Change the observations to see their center, spread, dot plot, histogram, and box plot. Try adding one extreme value.</p><label for="data-values">Numbers separated by commas (4–20 observations)</label><input id="data-values" class="answer-input" value="2, 4, 4, 6, 8, 10" style="width:100%;max-width:520px"><div class="controls"><button class="primary" id="data-update">Update displays</button><button class="ghost" id="data-extreme">Use an outlier example</button></div><p id="data-error" role="status"></p><div id="data-output"></div></section>`;}
function courseWireData(){
 const draw=()=>{
  const parts=document.getElementById('data-values').value.split(',').map(s=>s.trim()),a=parts.map(Number).sort((x,y)=>x-y);
  if(parts.some(s=>!s)||a.length<4||a.length>20||a.some(x=>!Number.isFinite(x)||Math.abs(x)>10000)){document.getElementById('data-error').textContent='Enter 4–20 finite numbers between −10,000 and 10,000, separated by commas.';return;}
  document.getElementById('data-error').textContent='';
  const mean=cm(a),median=cmed(a),m=Math.floor(a.length/2),q1=cmed(a.slice(0,m)),q3=cmed(a.slice(Math.ceil(a.length/2))),sd=Math.sqrt(cm(a.map(x=>(x-mean)**2))),iqr=q3-q1,f=n=>Number(n.toFixed(3)),min=a[0],max=a.at(-1),span=max-min||1,x=n=>50+(n-min)/span*520;
  const stacks={},dots=a.map(n=>{stacks[n]=(stacks[n]||0)+1;return `<circle cx="${x(n)}" cy="${250-stacks[n]*10}" r="4" fill="#24696b"/>`;}).join('');
  const counts=Array(4).fill(0);a.forEach(n=>counts[Math.min(3,Math.floor((n-min)/span*4))]++);
  const bins=counts.map((count,i)=>{const l=min+span*i/4,r=min+span*(i+1)/4;return {count,label:`[${f(l)}, ${f(r)}${i===3?']':')'}`};});
  const outliers=a.filter(n=>n<q1-1.5*iqr||n>q3+1.5*iqr);
  document.getElementById('data-output').innerHTML=`<p><strong>Sorted data:</strong> ${a.join(', ')}</p><div style="overflow-x:auto"><table style="width:100%;text-align:left"><thead><tr><th>Mean</th><th>Median</th><th>Q1</th><th>Q3</th><th>IQR</th><th>Population SD</th></tr></thead><tbody><tr>${[mean,median,q1,q3,iqr,sd].map(n=>`<td>${f(n)}</td>`).join('')}</tr></tbody></table></div><p class="muted">Results rounded to 3 decimals. Quartiles exclude the middle observation for an odd count. Population SD divides by n.</p><h3>Dot plot</h3><svg viewBox="0 0 620 290" role="img" aria-label="Dot plot. One dot per observation; sorted values listed above." style="width:100%;max-width:620px"><path d="M40 258H580" stroke="#536875"/>${dots}<text x="50" y="280">${min}</text><text x="570" y="280" text-anchor="end">${max}</text></svg><h3>Histogram</h3><svg viewBox="0 0 620 165" role="img" aria-label="Histogram with four equal-width intervals. Exact counts are listed below." style="width:100%;max-width:620px">${counts.map((c,i)=>`<rect x="${50+i*130}" y="${125-c/Math.max(...counts)*90}" width="128" height="${c/Math.max(...counts)*90}" fill="#86b9b1"/><text x="${114+i*130}" y="${116-c/Math.max(...counts)*90}" text-anchor="middle">${c}</text>`).join('')}<path d="M50 125H570" stroke="#536875"/><text x="50" y="150">${min}</text><text x="570" y="150" text-anchor="end">${max===min?min+1:max}</text></svg><p>${bins.map(b=>`${esc(b.label)}: ${b.count}`).join(' · ')}</p><p class="muted">Numbers above bars are frequencies. All intervals include their left endpoint; only the last includes its right endpoint.</p><h3>Box plot</h3><svg viewBox="0 0 620 100" role="img" aria-label="Box plot: minimum ${min}, Q1 ${f(q1)}, median ${f(median)}, Q3 ${f(q3)}, maximum ${max}." style="width:100%;max-width:620px"><path d="M${x(min)} 42H${x(max)}M${x(min)} 25V60M${x(max)} 25V60" stroke="#536875"/><rect x="${x(q1)}" y="20" width="${Math.max(1,x(q3)-x(q1))}" height="44" fill="#d6ece7" stroke="#24696b"/><path d="M${x(median)} 20V64" stroke="#123c4a" stroke-width="3"/><text x="50" y="88">${min}</text><text x="570" y="88" text-anchor="end">${max}</text></svg><p>Five-number summary: ${[min,q1,median,q3,max].map(f).join(', ')}. This simple box plot uses minimum and maximum as whiskers.</p><p><strong>1.5×IQR outlier flags:</strong> ${outliers.length?outliers.join(', '):'None'}. Fences: ${f(q1-1.5*iqr)} and ${f(q3+1.5*iqr)}.</p>`;
 };
 document.getElementById('data-update').onclick=draw;document.getElementById('data-extreme').onclick=()=>{document.getElementById('data-values').value='2, 4, 4, 6, 8, 40';draw();};draw();
}
