'use strict';
const U3_TABLE_SKILLS=['two-way-tables','relative-frequencies','categorical-association'];
function unit3Tool(id){
 if(id==='causation')return `<section class="card study-routine"><h2>Two different kinds of “random”</h2><div class="worked-grid"><article><h3>Random sampling</h3><p>Population → randomly selected sample → observations</p><p>Helps answer: “Whom might these results represent?”</p></article><article><h3>Random assignment</h3><p>Participants → randomly assigned groups → different treatments → compare outcomes</p><p>Helps answer: “Did the treatment affect the outcome?”</p></article></div><p class="hint">A study can use both, one, or neither. Check what the researchers actually did.</p></section>`;
 if(U3_TABLE_SKILLS.includes(id))return `<section class="card study-routine"><h2>Explore a two-way table</h2><p>Change the four counts. Switch the reference group to see why the denominator matters. All data here are invented.</p><div class="u3-inputs">${['Members · bus','Members · no bus','Nonmembers · bus','Nonmembers · no bus'].map((s,i)=>`<label>${s}<input type="number" id="u3-cell-${i}" min="0" max="1000" step="1" value="${[12,8,6,14][i]}"></label>`).join('')}<label>Display<select id="u3-mode"><option value="count">Counts</option><option value="all">Percent of everyone</option><option value="row">Percent within each row</option><option value="column">Percent within each column</option></select></label></div><p id="u3-error" role="status"></p><div id="u3-table-output"></div></section>`;
 return `<section class="card study-routine"><h2>Explore a scatter plot and its residuals</h2><p>Change the data or move the line. Read the correlation and prediction errors together. These are invented, unitless x/y observations.</p><div class="controls"><label>Data set<select id="u3-preset"><option value="positive">Positive pattern</option><option value="negative">Negative pattern</option><option value="curve">Curved pattern</option><option value="outlier">One unusual point</option></select></label><button class="ghost" id="u3-fit">Fit least-squares line</button></div><label for="u3-points">Paired observations: x,y; x,y (3–12 pairs; x: 0–10, y: 0–30)</label><input id="u3-points" class="answer-input u3-points" value="1,5; 2,6; 3,10; 4,10; 5,14; 6,15"><div class="controls"><button class="primary" id="u3-update">Use these points</button><label>Slope m <input id="u3-m" type="range" min="-10" max="10" step="0.01" value="2"></label><label>Intercept b <input id="u3-b" type="range" min="-50" max="50" step="0.01" value="3"></label></div><p id="u3-error" role="status"></p><p id="u3-model" aria-live="polite"></p><div id="u3-scatter-output"></div><p class="muted">The fit button uses least squares and rounds m and b to 2 decimals. Residual = observed − predicted. A strong correlation does not establish a cause.</p></section>`;
}
function u3Stats(points){
 const mx=cm(points.map(p=>p[0])),my=cm(points.map(p=>p[1]));
 let xx=0,yy=0,xy=0;for(const [x,y]of points){xx+=(x-mx)**2;yy+=(y-my)**2;xy+=(x-mx)*(y-my);}
 return {r:xx&&yy?Math.max(-1,Math.min(1,xy/Math.sqrt(xx*yy))):null,m:xx?xy/xx:null,b:xx?my-xy/xx*mx:null};
}
function unit3Wire(id){
 if(id==='causation')return;
 const el=s=>document.getElementById(s),f=n=>Number(n.toFixed(3));
 if(U3_TABLE_SKILLS.includes(id)){
  const draw=()=>{const a=[0,1,2,3].map(i=>el('u3-cell-'+i).value.trim());const c=a.map(Number);if(a.some(s=>s==='')||c.some(n=>!Number.isInteger(n)||n<0||n>1000)){el('u3-error').textContent='Enter four whole-number counts from 0 to 1000.';return;}el('u3-error').textContent='';const rows=[c[0]+c[1],c[2]+c[3]],cols=[c[0]+c[2],c[1]+c[3]],total=cm(rows)*2,mode=el('u3-mode').value;
   const cell=(n,r,col)=>mode==='count'?n:((mode==='all'?total:mode==='row'?rows[r]:cols[col])?f(100*n/(mode==='all'?total:mode==='row'?rows[r]:cols[col]))+'%':'Undefined');
   const totalCell=(n,kind)=>mode==='count'?n:mode==='all'?(total?f(n/total*100)+'%':'Undefined'):mode===kind?(n?'100%':'Undefined'):'—';
   el('u3-table-output').innerHTML=`<div class="u3-table-wrap"><table class="u3-table"><caption>${{count:'Counts of people',all:'Percent of everyone',row:'Percent within each row',column:'Percent within each column'}[mode]}</caption><thead><tr><th scope="col">Group</th><th scope="col">Bus</th><th scope="col">No bus</th><th scope="col">Row total</th></tr></thead><tbody>${rows.map((n,r)=>`<tr><th scope="row">${r?'Nonmembers':'Members'}</th><td>${cell(c[2*r],r,0)}</td><td>${cell(c[2*r+1],r,1)}</td><td>${totalCell(n,'row')}</td></tr>`).join('')}<tr><th scope="row">Column total</th>${cols.map(n=>`<td>${totalCell(n,'column')}</td>`).join('')}<td>${mode==='count'?total:mode==='all'?(total?'100%':'Undefined'):'—'}</td></tr></tbody></table></div><p>${mode==='count'?`There are ${total} people. Each interior cell counts one combination.`:mode==='all'?`Every interior count is divided by the grand total, ${total}.`:mode==='row'?`Member cells divide by ${rows[0]}; nonmember cells divide by ${rows[1]}.`:`Bus cells divide by ${cols[0]}; no-bus cells divide by ${cols[1]}.`} A zero denominator gives an undefined percentage.</p><p>${rows.every(n=>n>0)?`Bus-use rate among members: ${f(c[0]/rows[0]*100)}%. Among nonmembers: ${f(c[2]/rows[1]*100)}%. Difference (members minus nonmembers): ${f((c[0]/rows[0]-c[2]/rows[1])*100)} percentage points.`:'Both groups need at least one person to compare their bus-use rates.'}</p>`;
  };[0,1,2,3].forEach(i=>el('u3-cell-'+i).oninput=draw);el('u3-mode').onchange=draw;draw();return;
 }
 let points=[[1,5],[2,6],[3,10],[4,10],[5,14],[6,15]];
 const presets={positive:points,negative:[[1,17],[2,14],[3,13],[4,9],[5,8],[6,4]],curve:[[1,18],[2,11],[3,6],[4,3],[5,2],[6,3],[7,6],[8,11],[9,18]],outlier:[[1,5],[2,7],[3,9],[4,11],[5,13],[9,2]]};
 function draw(){const m=+el('u3-m').value,b=+el('u3-b').value,stats=u3Stats(points),res=points.map(([x,y])=>[x,y,m*x+b,y-(m*x+b)]),sse=res.reduce((s,p)=>s+p[3]**2,0),maxR=Math.max(1,...res.map(p=>Math.abs(p[3]))),x=n=>55+n*50,y=n=>295-n*8.2,ry=n=>440-n/maxR*55;
 el('u3-model').textContent=`Model: ŷ = ${f(m)}x ${b<0?'−':'+'} ${f(Math.abs(b))}. r = ${stats.r===null?'undefined':f(stats.r)}. Sum of squared residuals = ${f(sse)}.`;
 el('u3-scatter-output').innerHTML=`<svg class="u3-chart" viewBox="0 0 620 545" role="img" aria-label="Scatter plot with a fitted line, vertical residuals, and a residual plot. All exact plotted values are in the table below."><defs><clipPath id="u3-clip"><rect x="55" y="49" width="500" height="246"/></clipPath></defs>${[0,5,10,15,20,25,30].map(n=>`<path d="M55 ${y(n)}H555" stroke="#e2e7e8"/><text x="45" y="${y(n)+4}" text-anchor="end">${n}</text>`).join('')}<path d="M55 49V295H555" stroke="#536875"/><text x="55" y="28">Observed y</text><text x="280" y="338">Input x</text>${[0,2,4,6,8,10].map(n=>`<text x="${x(n)}" y="317" text-anchor="middle">${n}</text>`).join('')}<g clip-path="url(#u3-clip)"><path d="M${x(0)} ${y(b)}L${x(10)} ${y(m*10+b)}" stroke="#24696b" stroke-width="3"/>${res.map(([a,v,p])=>`<path d="M${x(a)} ${y(v)}V${y(p)}" stroke="#ad793c" stroke-width="2" stroke-dasharray="4 3"/><circle cx="${x(a)}" cy="${y(v)}" r="5" fill="#183e55"/>`).join('')}</g><text x="55" y="367">Residual (observed − predicted)</text><path d="M55 380V500M55 440H555" stroke="#536875"/>${[-maxR,0,maxR].map(n=>`<text x="45" y="${ry(n)+4}" text-anchor="end">${f(n)}</text>`).join('')}${res.map(([a,v,p,r])=>`<circle cx="${x(a)}" cy="${ry(r)}" r="5" fill="#ad793c"/>`).join('')}${[0,2,4,6,8,10].map(n=>`<text x="${x(n)}" y="519" text-anchor="middle">${n}</text>`).join('')}<text x="280" y="541">Input x</text></svg><p class="muted">Blue dots: observations. Green line: predictions. Dashed segments: residuals. The residual plot’s vertical scale adjusts to show all errors. Predictions outside the top chart’s y-range are clipped there but remain in the table.</p><div class="u3-table-wrap"><table class="u3-table"><caption>Paired observations and predictions (rounded to 3 decimals)</caption><thead><tr><th>x</th><th>Observed y</th><th>Predicted ŷ</th><th>Residual</th></tr></thead><tbody>${res.map(row=>`<tr>${row.map(n=>`<td>${f(n)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
 }
 function read(){const raw=el('u3-points').value.split(';').map(s=>s.trim().split(',').map(s=>s.trim()));const a=raw.map(p=>p.map(Number));if(a.length<3||a.length>12||raw.some(p=>p.length!==2||p.some(s=>!s))||a.some(p=>p.some(n=>!Number.isFinite(n))||p[0]<0||p[0]>10||p[1]<0||p[1]>30)){el('u3-error').textContent='Use 3–12 pairs such as 1,5; 2,6; 3,10. x must be 0–10 and y must be 0–30.';return false;}points=a;el('u3-error').textContent='';return true;}
 el('u3-update').onclick=()=>{if(read())draw();};el('u3-m').oninput=draw;el('u3-b').oninput=draw;
 el('u3-preset').onchange=e=>{points=presets[e.target.value].map(p=>[...p]);el('u3-points').value=points.map(p=>p.join(',')).join('; ');el('u3-error').textContent='';draw();};
 el('u3-fit').onclick=()=>{if(!read())return;const s=u3Stats(points);if(s.m===null){el('u3-error').textContent='A prediction line needs at least two different x-values. Correlation is also undefined when x is constant.';draw();return;}for(const [key,value]of [['u3-m',s.m],['u3-b',s.b]]){const input=el(key);input.min=Math.min(Number(input.min),Math.floor(value));input.max=Math.max(Number(input.max),Math.ceil(value));input.value=value.toFixed(2);}draw();};draw();
}
