'use strict';
const svg=(body,label,h=280)=>`<svg viewBox="0 0 600 ${h}" role="img" aria-label="${esc(label)}" xmlns="http://www.w3.org/2000/svg"><defs><marker id="arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0 0L8 4L0 8Z" fill="#446d61"/></marker></defs>${body}</svg>`;
const textSVG=(x,y,t,size=18)=>`<text x="${x}" y="${y}" text-anchor="middle" font-size="${size}" fill="#183d36">${esc(t)}</text>`;
const box=(x,y,w,h,t,fill='#e4eee5')=>`<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="14" fill="${fill}" stroke="#789787"/>${textSVG(x+w/2,y+h/2+6,t)}`;
const line=(x,y,a,b)=>`<path d="M${x} ${y}L${a} ${b}" fill="none" stroke="#446d61" stroke-width="2" marker-end="url(#arrow)"/>`;
const VISUAL_NAMES={experiment:'Read an experiment',enzyme:'Enzyme activity explorer',web:'Explore a food web',population:'Population growth model',energy:'Follow matter and energy',cell:'Explore a living cell',membrane:'Which way will water move?',systems:'A sprint is a team effort',feedback:'Trace a feedback loop',dna:'DNA base-pair builder',division:'Compare cell divisions',punnett:'Build a Punnett square',selection:'Selection over generations',tree:'Read a family tree of life'};
const LESSON_VISUAL_NAMES={
 investigations:'Build a fair investigation',
 evidence:'Read data and build an explanation',
 biodiversity:'Watch an ecosystem respond to disturbance',
 'human-impacts':'Trace runoff from cause to consequence',
 photosynthesis:'Follow carbon into a plant',
 respiration:'Follow energy through a mitochondrion',
 'food-energy':'Build an energy pyramid',
 'carbon-cycle':'Trace carbon through Earth systems',
 dna:'Zoom from a cell to DNA',
 proteins:'Follow DNA → RNA → protein',
 mutations:'See how a sequence change can matter',
 mitosis:'Step through mitosis',
 meiosis:'Step through meiosis',
 'evolution-evidence':'Combine evidence for common ancestry',
 speciation:'Watch populations diverge'
};
const REAL_LIFE={
 cells:{
  title:"Cells under real microscopes",
  intro:"Compare the clean teaching model with real biological tissue. Real microscope images are messier because cells overlap, stain differently, and rarely show every organelle at once.",
  exam:"Start with the large clues: cell boundary, nucleus, and tissue pattern. Do not expect a real cell to look as clean or complete as a textbook diagram.",
  images:[
   {src:"assets/real-life/animal-cell-electron-micrograph.jpg",alt:"Transmission electron micrograph of an animal pancreatic cell showing internal structures",label:"Animal cell · electron micrograph",note:"The nucleus is the most obvious structure. Rough endoplasmic reticulum surrounds it, and a mitochondrion is also visible."},
   {src:"assets/real-life/plant-cells-light-micrograph.jpg",alt:"Light micrograph of plant collenchyma tissue showing many cells and thickened cell walls",label:"Plant cells · light micrograph",note:"Look for repeated cell boundaries and the thicker cell walls. Real plant tissue is a packed group of cells, not one isolated diagram."}
  ]
 },
 transport:{
  title:"Osmosis in a living cell",
  intro:"This is a microscope view connected to the same water-balance idea shown in the membrane model.",
  exam:"In a hypotonic environment, water tends to enter the cell. Connect what you see to the response that prevents too much water from accumulating.",
  images:[
   {src:"assets/real-life/osmosis-paramecium-micrograph.jpg",alt:"Bright-field microscope image of a Paramecium with a contractile vacuole",label:"Paramecium · bright-field microscope",note:"A contractile vacuole pumps excess water out. It is a real example of a cell managing water that enters by osmosis."}
  ]
 },
 dna:{
  title:"DNA when it is packaged into chromosomes",
  intro:"The familiar double helix is a molecular model. In cells, long DNA molecules are wrapped around proteins and can condense into chromosomes.",
  exam:"On microscope questions, DNA usually appears as chromatin or condensed chromosomes—not as a giant visible double helix. Chromosome shape and number are the clues.",
  images:[
   {src:"assets/real-life/human-chromosomes-fluorescence.jpg",alt:"Fluorescence image of human chromosomes stained in different colors",label:"Human chromosomes · fluorescence imaging",note:"These are condensed human chromosomes marked with fluorescent stains. Each chromosome contains one long DNA molecule packaged with proteins."}
  ]
 },
 mitosis:{
  title:"Mitosis under fluorescence microscopy",
  intro:"The real microscope images in this reference show chromosomes and spindle structures during cell division.",
  exam:"Identify the stage from chromosome position, not from the artificial colors: middle = metaphase; separating = anaphase; two groups at opposite ends = late mitosis.",
  images:[
   {src:"assets/real-life/mitosis-fluorescence.png",alt:"Reference image containing fluorescence micrographs of cells in stages of mitosis",label:"Mitosis · fluorescence microscopy",note:"Blue fluorescence marks DNA/chromosomes and green marks spindle microtubules. The colors come from fluorescent labels used by scientists."}
  ]
 },
 "evolution-evidence":{
  title:"Fossil evidence you can actually see",
  intro:"Fossils are one physical line of evidence scientists combine with anatomy and DNA when reconstructing evolutionary relationships.",
  exam:"A fossil alone does not draw the family tree. Use preserved structures together with homologous anatomy and molecular evidence to support common ancestry.",
  images:[
   {src:"assets/real-life/archaeopteryx-fossil.jpg",alt:"Archaeopteryx reference image including a fossil with preserved skeletal and feather structures",label:"Archaeopteryx · fossil evidence",note:"The fossil portion preserves skeletal and feather features. Fossils let scientists compare structures across organisms and through time."}
  ]
 }
};
function realLifePanel(lessonId){
 const d=REAL_LIFE[lessonId];if(!d)return '';
 return `<dialog class="real-life-dialog" id="real-life-dialog" aria-labelledby="real-life-title"><div class="real-life-shell"><div class="real-life-head"><div><p class="eyebrow">REAL BIOLOGY · EXAM RECOGNITION</p><h2 id="real-life-title">${d.title}</h2></div><button type="button" class="soft real-life-close" id="real-life-close" aria-label="Close real-life images">Close</button></div><p class="real-life-intro">${d.intro}</p><div class="real-life-gallery">${d.images.map(x=>`<figure class="real-life-figure"><img src="${x.src}" alt="${x.alt}" loading="lazy"><figcaption><strong>${x.label}</strong><span>${x.note}</span></figcaption></figure>`).join('')}</div><aside class="real-life-exam"><strong>Exam tip</strong><p>${d.exam}</p></aside><p class="small muted real-life-credit">These image files are stored inside Ethan Study Hub. Source and license details are recorded in <code>assets/real-life/SOURCES.md</code>.</p></div></dialog>`;
}
function bindRealLife(lessonId){
 const dialog=document.getElementById('real-life-dialog'),open=document.getElementById('real-life-open');if(!dialog||!open||!REAL_LIFE[lessonId])return;
 const close=document.getElementById('real-life-close');
 const shut=()=>{if(typeof dialog.close==='function')dialog.close();else dialog.removeAttribute('open');};
 open.onclick=()=>{if(typeof dialog.showModal==='function')dialog.showModal();else dialog.setAttribute('open','');};
 close.onclick=shut;
 dialog.addEventListener('click',e=>{if(e.target===dialog)shut();});
}
function visualPanel(type,lessonId){const real=REAL_LIFE[lessonId],title=LESSON_VISUAL_NAMES[lessonId]||VISUAL_NAMES[type];return `<section class="visual card"><div class="section-top"><div><p class="eyebrow">SEE IT · CHANGE IT · EXPLAIN IT</p><h2>${title}</h2></div><div class="visual-head-actions"><span class="tag">Interactive</span>${real?'<button type="button" class="soft real-life-trigger" id="real-life-open" title="Compare this diagram with real biology">📷 Real image</button>':''}</div></div><div id="visual-controls" class="controls"></div><div id="visual-drawing" class="drawing"></div><p id="visual-caption" class="visual-caption" role="status" aria-live="polite"></p><p class="small muted">Simplified learning model. Read the explanation and assumptions below the image.</p></section>${realLifePanel(lessonId)}`;}
function mountVisual(type,lessonId){
 const controls=document.getElementById('visual-controls'),drawing=document.getElementById('visual-drawing'),caption=document.getElementById('visual-caption');if(!controls)return;bindRealLife(lessonId);
 const buttons=(items,fn)=>{controls.innerHTML=items.map(([value,label])=>`<button class="soft" data-value="${value}">${label}</button>`).join('');controls.querySelectorAll('button').forEach(b=>b.onclick=()=>{controls.querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));fn(b.dataset.value);});controls.querySelector('button').click();};

 // Lesson-specific models prevent different concepts from feeling like the same page.
 if(lessonId==='investigations')return buttons([['fair','Fair test'],['confounded','Confounded test']],mode=>{
  const bad=mode==='confounded';
  drawing.innerHTML=svg(`${box(35,48,220,62,'Group A · 8 h light','#e6eedf')}${box(345,48,220,62,'Group B · 2 h light','#efe3c8')}${textSVG(300,28,'Question: Does light affect seedling growth?',17)}${textSVG(145,145,'Water: 100 mL',14)}${textSVG(455,145,bad?'Water: 50 mL':'Water: 100 mL',14)}${textSVG(145,174,'Same soil · same species',14)}${textSVG(455,174,'Same soil · same species',14)}${line(145,188,145,235)}${line(455,188,455,235)}${box(65,235,160,48,'Measure height','#d8e8e5')}${box(375,235,160,48,'Measure height','#d8e8e5')}`,bad?'Two plant groups differ in both light and water, so the test is confounded.':'Two plant groups differ in light while relevant conditions are kept comparable.',310);
  caption.textContent=bad?'This is not a fair test: both light and water changed, so either could help explain a growth difference.':'Independent variable: light exposure. Dependent variable: height gained. Water, soil, species, timing, and measurement method are controlled as closely as practical.';
 });
 if(lessonId==='biodiversity')return buttons([['before','Before disturbance'],['after','After disturbance'],['recover','Recovery']],mode=>{
  const species=['#547c58','#7f6c9a','#c99355','#6c95a0'];
  const dots=(count,y,offset=0)=>Array.from({length:count},(_,i)=>`<circle cx="${75+(i%8)*58}" cy="${y+Math.floor(i/8)*48}" r="15" fill="${species[(i+offset)%species.length]}" opacity=".9"/>`).join('');
  const body=mode==='before'?dots(24,65):mode==='after'?dots(9,85,1):dots(18,70,2);
  drawing.innerHTML=svg(`<rect x="45" y="35" width="510" height="205" rx="24" fill="#edf2e8"/>${body}${textSVG(300,275,mode==='before'?'Many species and roles before disturbance':mode==='after'?'Disturbance reduces populations and changes composition':'Some populations return; the community may reorganize',16)}`,'Schematic community before, immediately after, and during recovery from a disturbance.',300);
  caption.textContent=mode==='before'?'Biodiversity includes genetic, species, and ecosystem variation. More kinds of organisms can create alternate pathways, but resilience is not guaranteed.':mode==='after'?'A disturbance can remove organisms and resources unevenly. The ecosystem is changed, not simply paused.':'Recovery can restore functions without recreating the exact original community. Starting conditions, surviving organisms, and later conditions matter.';
 });
 if(lessonId==='human-impacts')return buttons([['runoff','Nutrient runoff'],['buffer','Vegetated buffer']],mode=>{
  const buffered=mode==='buffer';
  drawing.innerHTML=svg(`${box(25,45,145,62,'Farm / lawn','#ead9b8')}${line(170,76,270,76)}${box(270,45,150,62,buffered?'Vegetated buffer':'Nutrients enter stream',buffered?'#d6e8ce':'#efd0ba')}${line(420,76,520,76)}${box(450,135,125,60,buffered?'Clearer water':'Algal growth',buffered?'#d9eaeb':'#d9df9c')}${line(510,195,395,235)}${box(245,225,190,55,buffered?'More stable O₂':'Decomposition uses O₂',buffered?'#d9eaeb':'#e8d1c8')}${textSVG(300,315,buffered?'A buffer can reduce runoff before it reaches water':'Extra nutrients can trigger a chain of effects',16)}`,'Simplified nutrient-runoff pathway and one possible conservation intervention.',340);
  caption.textContent=buffered?'A vegetated buffer can slow runoff and trap some sediment and nutrients. Effectiveness depends on width, plants, slope, weather, and maintenance; monitoring is still needed.':'Nutrient enrichment can increase algal biomass. When organic material is decomposed, microbial respiration can lower dissolved oxygen and stress aquatic organisms.';
 });
 if(lessonId==='food-energy'){
  controls.innerHTML='<label>Transfer efficiency <input id="efficiency" type="range" min="5" max="20" value="10"><output id="efficiency-value"></output></label>';
  const draw=()=>{const e=+document.getElementById('efficiency').value/100;document.getElementById('efficiency-value').textContent=Math.round(e*100)+'%';const vals=[10000,10000*e,10000*e*e,10000*e*e*e].map(v=>Math.round(v));drawing.innerHTML=svg(`<polygon points="300,25 75,245 525,245" fill="#edf1df" stroke="#69806e"/><path d="M125 195H475M185 135H415M245 75H355" stroke="#fff" stroke-width="5"/>${textSVG(300,225,`Producers · ${vals[0]} units`,16)}${textSVG(300,175,`Primary consumers · ${vals[1]}`,15)}${textSVG(300,116,`Secondary · ${vals[2]}`,15)}${textSVG(300,58,`Tertiary · ${vals[3]}`,14)}`,'Energy pyramid with a user-selected transfer efficiency.',275);caption.textContent=`At ${Math.round(e*100)}% transfer, only part of one trophic level's stored chemical energy becomes biomass available to the next. The familiar 10% value is a rough teaching approximation, not a universal law.`;};document.getElementById('efficiency').oninput=draw;draw();return;
 }
 if(lessonId==='photosynthesis')return buttons([['carbon','Trace carbon'],['oxygen','Trace oxygen']],mode=>{
  const carbon=mode==='carbon';
  drawing.innerHTML=svg(`${box(25,35,150,58,carbon?'CO₂ from air':'H₂O from roots','#d8e8e5')}${line(175,64,280,115)}${box(220,105,165,78,'Chloroplast','#dbe8c7')}${textSVG(302,138,'light energy',15)}${line(385,145,500,80)}${box(430,40,140,58,carbon?'Sugar carbon':'O₂ released','#efe3c8')}${textSVG(300,225,carbon?'Carbon atoms become part of organic molecules':'Water contributes electrons; oxygen gas is released',16)}`,'Simplified photosynthesis showing different matter pathways through a chloroplast.',255);
  caption.textContent=carbon?'The carbon in plant dry mass comes largely from CO₂. Light supplies energy; it is not a source of carbon atoms.':'In the full photosynthetic process, the oxygen released as O₂ comes from water. This model focuses on inputs and outputs rather than the detailed reactions.';
 });
 if(lessonId==='respiration')return buttons([['rest','Resting cell'],['sprint','Working muscle']],mode=>{
  const sprint=mode==='sprint';
  drawing.innerHTML=svg(`${box(25,70,145,60,'Glucose / fuel','#efe3c8')}${box(25,160,145,60,'O₂','#d8e8e5')}${line(170,100,275,135)}${line(170,190,275,155)}<ellipse cx="355" cy="145" rx="92" ry="58" fill="#efd1a9" stroke="#9d7448"/><path d="M290 145q25-35 50 0t50 0t50 0" fill="none" stroke="#a66f3e" stroke-width="4"/>${textSVG(355,150,'Mitochondrion',16)}${line(447,120,540,75)}${line(447,165,540,205)}${textSVG(535,62,sprint?'More ATP demand':'ATP for cell work',15)}${textSVG(535,225,'CO₂ + H₂O + heat',14)}${textSVG(300,270,sprint?'During a sprint, ATP use rises rapidly':'Cells need ATP even at rest',16)}`,'Simplified cellular respiration connecting fuel and oxygen to ATP, carbon dioxide, water, and heat.',295);
  caption.textContent=sprint?'Muscle contraction uses ATP quickly. Respiration helps replenish ATP, while breathing and circulation support oxygen delivery and carbon-dioxide removal.':'Cellular respiration transfers chemical energy from fuels into ATP and heat. Mitochondria do not create energy; they participate in energy transformations.';
 });
 if(lessonId==='carbon-cycle')return buttons([['natural','Natural transfers'],['human','Add fossil-fuel combustion']],mode=>{
  const human=mode==='human';
  drawing.innerHTML=svg(`${box(205,20,190,52,'Atmosphere CO₂','#d4e8ed')}${box(25,135,145,58,'Plants','#dce8d3')}${box(225,135,145,58,'Animals','#eadcc6')}${box(430,135,145,58,'Ocean','#d7e7ef')}${box(90,245,155,55,'Soils / decomposers','#e5dcc9')}${box(360,245,155,55,'Fossil carbon','#ddd6ca')}${line(220,72,140,134)}${line(170,164,225,164)}${line(298,135,285,74)}${line(475,135,365,73)}${line(160,194,170,244)}${line(305,194,205,245)}${human?line(438,245,330,75):''}${human?textSVG(440,225,'combustion',13):''}${textSVG(300,330,human?'Rapid transfer from long-term stores can raise atmospheric CO₂':'Carbon continually moves among reservoirs at different rates',15)}`,'Carbon reservoirs and selected transfer pathways.',350);
  caption.textContent=human?'Combustion transfers carbon from long-term geological stores into the atmosphere relatively quickly. Carbon is conserved, but the amount stored in each reservoir can change.':'Photosynthesis, feeding, respiration, decomposition, and ocean exchange move carbon among reservoirs. The arrows represent transfers, not equal rates.';
 });
 if(lessonId==='dna')return buttons([['cell','Cell'],['nucleus','Nucleus'],['chromosome','Chromosome'],['dna','DNA']],mode=>{
  const order=['cell','nucleus','chromosome','dna'],idx=order.indexOf(mode),fills=['#d8e8e5','#d9cce8','#c9c4e8','#ead39c'];
  drawing.innerHTML=svg(order.map((x,i)=>`${box(25+i*145,105,120,70,x[0].toUpperCase()+x.slice(1),i===idx?fills[i]:'#f4f5ef')}${i<3?line(145+i*145,140,170+i*145,140):''}`).join('')+`${textSVG(300,225,'cell → nucleus → chromosome → DNA',18)}`,'Hierarchy from a cell to its nucleus, chromosome, and DNA.',250);
  caption.textContent={cell:'A human body cell contains a nucleus and many other structures.',nucleus:'The nucleus contains most of the cell’s DNA packaged with proteins.',chromosome:'A chromosome is one long DNA molecule packaged with proteins; chromosomes are most visibly condensed during cell division.',dna:'DNA is the information-carrying molecule. A gene is a DNA sequence with a biological function, not a separate object floating beside DNA.'}[mode];
 });
 if(lessonId==='proteins')return buttons([['transcription','1 · Transcription'],['translation','2 · Translation']],mode=>{
  const trans=mode==='transcription';
  drawing.innerHTML=svg(`${box(25,80,145,65,'DNA','#d8cde5')}${line(170,112,275,112)}${box(275,80,145,65,'mRNA',trans?'#e6d9ef':'#d9e8e5')}${line(420,112,520,112)}${box(455,185,120,60,'Protein','#ead9aa')}${trans?textSVG(220,90,'transcribe',14):textSVG(470,160,'ribosome translates',14)}${!trans?'<circle cx="510" cy="112" r="28" fill="#bdd7cf" stroke="#648678"/>'+textSVG(510,118,'ribosome',12):''}${textSVG(300,270,trans?'DNA information is copied into RNA':'mRNA codons guide amino-acid order',16)}`,'Simplified path from DNA to mRNA to protein.',295);
  caption.textContent=trans?'In a typical eukaryotic cell, transcription makes RNA from a DNA template in the nucleus. RNA processing can produce mRNA for export.':'A ribosome reads mRNA codons and tRNAs help deliver amino acids. The polypeptide then folds and may be modified before becoming functional.';
 });
 if(lessonId==='mutations')return buttons([['sub','Substitution'],['ins','Insertion'],['del','Deletion']],mode=>{
  const original='ATG CCA GTT',changed=mode==='sub'?'ATG CTA GTT':mode==='ins'?'ATG ACC AGT T':'ATG CAG TT';
  drawing.innerHTML=svg(`${box(55,55,490,60,'Original · '+original,'#e9e4f0')}${line(300,118,300,165)}${box(55,165,490,60,(mode==='sub'?'Substitution':mode==='ins'?'Insertion':'Deletion')+' · '+changed,mode==='sub'?'#e7e3c7':'#efd5cc')}${textSVG(300,270,mode==='sub'?'One base changes; protein effect may be none or substantial':'Reading groups can shift if bases are added or removed outside multiples of three',15)}`,'Comparison of an original sequence and a simplified mutated sequence.',295);
  caption.textContent=mode==='sub'?'A substitution replaces one base. Because the genetic code is redundant, some substitutions do not change the amino acid; others can change function or regulation.':mode==='ins'?'An insertion can shift the reading frame if the number of inserted bases is not divisible by three. Effects depend on location and context.':'A deletion can shift the reading frame if the number removed is not divisible by three. Mutations are changes in sequence; their biological effects vary.';
 });
 if(lessonId==='mitosis')return buttons([['interphase','Before mitosis'],['metaphase','Metaphase'],['anaphase','Anaphase'],['cytokinesis','Cytokinesis']],mode=>{
  const chromosomes=(xs,y)=>xs.map(x=>`<path d="M${x-8} ${y-18}l16 36m0-36-16 36" stroke="#7d6293" stroke-width="6"/>`).join('');
  let body='';
  if(mode==='interphase')body=`<circle cx="300" cy="145" r="95" fill="#e3eee9" stroke="#6d8b7d"/><circle cx="300" cy="145" r="48" fill="#d9cce7"/>${textSVG(300,151,'DNA copied in S phase',15)}`;
  if(mode==='metaphase')body=`<circle cx="300" cy="145" r="95" fill="#e3eee9" stroke="#6d8b7d"/>${chromosomes([260,285,315,340],145)}<path d="M205 145H255M345 145H395" stroke="#b88b48" stroke-width="2"/>`;
  if(mode==='anaphase')body=`<circle cx="300" cy="145" r="95" fill="#e3eee9" stroke="#6d8b7d"/>${chromosomes([235,255],145)}${chromosomes([345,365],145)}${line(285,145,220,145)}${line(315,145,380,145)}`;
  if(mode==='cytokinesis')body=`<circle cx="245" cy="145" r="72" fill="#e3eee9" stroke="#6d8b7d"/><circle cx="355" cy="145" r="72" fill="#e3eee9" stroke="#6d8b7d"/>${textSVG(245,150,'same set',14)}${textSVG(355,150,'same set',14)}`;
  drawing.innerHTML=svg(body+`${textSVG(300,275,mode==='interphase'?'DNA replication prepares the chromosomes':mode==='metaphase'?'Duplicated chromosomes line up':mode==='anaphase'?'Sister chromatids separate':'Two daughter cells form',16)}`,'Simplified sequence of mitosis and cytokinesis.',300);
  caption.textContent={interphase:'DNA is copied before mitosis during the cell cycle.',metaphase:'Duplicated chromosomes align so spindle attachments can organize separation.',anaphase:'Sister chromatids move toward opposite sides of the cell.',cytokinesis:'Cytokinesis divides the cytoplasm. Normal mitosis preserves chromosome number in the daughter cells.'}[mode];
 });
 if(lessonId==='meiosis')return buttons([['pair','Homologous pairs'],['cross','Crossing over'],['first','Meiosis I'],['second','Meiosis II']],mode=>{
  let body='';
  if(mode==='pair')body=`${box(65,85,205,90,'Maternal homolog','#e8d6e8')}${box(330,85,205,90,'Paternal homolog','#d7e7e1')}${textSVG(300,225,'same genes · possibly different alleles',16)}`;
  if(mode==='cross')body=`<path d="M190 65L270 215M270 65L190 215" stroke="#8f6ba0" stroke-width="9"/><path d="M330 65L410 215M410 65L330 215" stroke="#5e8b7a" stroke-width="9"/><path d="M255 120L345 160M345 120L255 160" stroke="#c48c55" stroke-width="5"/>${textSVG(300,250,'homologs can exchange DNA',16)}`;
  if(mode==='first')body=`<circle cx="210" cy="145" r="72" fill="#e7deee" stroke="#70877c"/><circle cx="390" cy="145" r="72" fill="#e1ece5" stroke="#70877c"/>${textSVG(210,150,'one homolog/set',14)}${textSVG(390,150,'other homolog/set',14)}`;
  if(mode==='second')body=[120,240,360,480].map(x=>`<circle cx="${x}" cy="145" r="48" fill="#e5eee2" stroke="#70877c"/>`).join('')+`${textSVG(300,230,'four haploid products',17)}`;
  drawing.innerHTML=svg(body,'Simplified sequence showing homolog pairing, crossing over, meiosis I, and meiosis II.',270);
  caption.textContent={pair:'Homologous chromosomes carry corresponding genes but can have different alleles.',cross:'Crossing over exchanges DNA between homologous chromosomes, creating new combinations along chromosomes.',first:'Meiosis I separates homologous chromosomes and reduces the chromosome-set number.',second:'Meiosis II separates sister chromatids, producing four haploid products in this simplified model.'}[mode];
 });
 if(lessonId==='evolution-evidence')return buttons([['fossil','Fossils'],['anatomy','Anatomy'],['dna','DNA'],['tree','Combine evidence']],mode=>{
  const content=mode==='fossil'?[`Past organism`,`dated rock layer`,`changes through time`]:mode==='anatomy'?[`same bone pattern`,`different functions`,`homology`]:mode==='dna'?[`sequence A · 96%`,`sequence B · 95%`,`compare many sites`]:[`fossils`,`anatomy`,`DNA`];
  drawing.innerHTML=svg(`${box(55,60,150,70,content[0],mode==='fossil'?'#e6d5bd':'#e4eee5')}${box(225,60,150,70,content[1],mode==='anatomy'?'#ddd5ea':'#e4eee5')}${box(395,60,150,70,content[2],mode==='dna'?'#d5e3ee':'#e4eee5')}${line(130,132,255,210)}${line(300,132,300,210)}${line(470,132,345,210)}${box(215,210,170,55,'Common ancestry','#dce9d4')}`,`Evidence source: ${mode}`,285);
  caption.textContent=mode==='tree'?'Confidence is strongest when independent evidence sources agree. A phylogenetic tree is a model built from evidence, not a photograph of ancestry.':mode==='fossil'?'Fossils document past organisms and can reveal sequences of structural change through time.':mode==='anatomy'?'Homologous structures can retain a shared underlying pattern even when their functions differ.':'DNA sequence comparisons provide molecular evidence of relationships; use appropriate genes and broader evidence, not one superficial similarity.';
 });
 if(lessonId==='speciation')return buttons([['connected','Gene flow'],['isolated','Barrier appears'],['later','Generations later']],mode=>{
  const barrier=mode!=='connected'?'<path d="M295 35L275 245H325L305 35Z" fill="#c8b9a0" stroke="#8f795e"/>':'';
  const left=Array.from({length:12},(_,i)=>`<circle cx="${85+(i%4)*42}" cy="${75+Math.floor(i/4)*55}" r="13" fill="${i%3===0?'#8b719e':'#6f9477'}"/>`).join('');
  const right=Array.from({length:12},(_,i)=>`<circle cx="${385+(i%4)*42}" cy="${75+Math.floor(i/4)*55}" r="13" fill="${mode==='later'?(i%4===0?'#c18c55':'#7093a0'):(i%3===0?'#8b719e':'#6f9477')}"/>`).join('');
  drawing.innerHTML=svg(`${left}${right}${barrier}${mode==='connected'?'<path d="M250 145H350" stroke="#446d61" stroke-width="3" marker-end="url(#arrow)"/><path d="M350 175H250" stroke="#446d61" stroke-width="3" marker-end="url(#arrow)"/>':''}${textSVG(150,260,'Population A',15)}${textSVG(450,260,'Population B',15)}`,'Two populations shown with gene flow, geographic isolation, and divergence over generations.',285);
  caption.textContent=mode==='connected'?'Gene flow moves alleles between reproducing populations and can keep them genetically similar.':mode==='isolated'?'A barrier can reduce gene flow, but isolation alone does not instantly create a new species.':'With reduced gene flow, mutation, drift, and selection can make populations diverge. Speciation requires the evolution of reproductive isolation or other evidence appropriate to the species concept.';
 });
 if(type==='cell'){
 let plant=false,part='nucleus';const descriptions={nucleus:'Nucleus: contains most DNA in a eukaryotic cell and is a site of transcription.',mitochondrion:'Mitochondrion: participates in aerobic respiration. Both plant and animal cells have mitochondria.',membrane:'Cell membrane: selectively regulates exchange. Plant cells also have a wall outside the membrane.',ribosome:'Ribosomes: assemble proteins. They occur in plant, animal, and prokaryotic cells.',chloroplast:'Chloroplast: uses light in photosynthesis. This is a typical photosynthetic plant cell; not all plant cells contain chloroplasts.',vacuole:'Large central vacuole: stores material and helps support a plant cell through water pressure.'};
 controls.innerHTML='<label>Cell type <select id="cell-type"><option value="animal">Animal cell</option><option value="plant">Photosynthetic plant cell</option></select></label><div id="cell-parts" class="controls"></div>';
 const draw=()=>{const parts=['nucleus','mitochondrion','membrane','ribosome',...(plant?['chloroplast','vacuole']:[])];if(!parts.includes(part))part='nucleus';document.getElementById('cell-parts').innerHTML=parts.map(p=>`<button class="soft" data-part="${p}" aria-pressed="${part===p}">${p[0].toUpperCase()+p.slice(1)}</button>`).join('');const highlight=p=>part===p?'stroke="#173f35" stroke-width="5"':'stroke="#6a9181" stroke-width="2"';drawing.innerHTML=svg(`${plant?'<rect x="95" y="15" width="410" height="255" rx="35" fill="#acc493" stroke="#5d794d" stroke-width="8"/>':''}<rect x="${plant?105:110}" y="25" width="${plant?390:380}" height="235" rx="${plant?30:115}" fill="#e3eee1" ${highlight('membrane')}/>${plant?`<rect x="260" y="63" width="195" height="155" rx="25" fill="#c8e1e9" ${highlight('vacuole')}/>`:''}<ellipse cx="230" cy="133" rx="56" ry="48" fill="#d1c0df" ${highlight('nucleus')}/><circle cx="227" cy="132" r="17" fill="#9c85af"/><ellipse cx="340" cy="220" rx="38" ry="17" fill="#efc598" ${highlight('mitochondrion')}/><path d="M310 220l10-8 10 16 10-16 10 16 10-8" stroke="#aa7445" fill="none"/>${[ [155,100],[168,173],[295,70],[394,45],[285,235] ].map(([x,y])=>`<circle cx="${x}" cy="${y}" r="5" fill="#735f7e" ${part==='ribosome'?'stroke="#183d36" stroke-width="3"':''}/>`).join('')}${plant?`<ellipse cx="170" cy="220" rx="35" ry="14" fill="#8ab983" ${highlight('chloroplast')}/><path d="M148 214h44m-44 6h44m-44 6h44" stroke="#3c7750"/>`:''}${textSVG(300,295,plant?'Plant cell schematic':'Animal cell schematic')}`, 'Schematic cell. Select a named structure to highlight it and read its role.',320);caption.textContent=descriptions[part]+' Other structures are omitted; shapes and sizes are simplified.';document.querySelectorAll('[data-part]').forEach(b=>b.onclick=()=>{part=b.dataset.part;draw();});};document.getElementById('cell-type').onchange=e=>{plant=e.target.value==='plant';draw();};draw();return;
 }
 if(type==='membrane'){
 controls.innerHTML='<label>Outside solute concentration <input type="range" id="solute" min="0" max="10" value="8"><output id="solute-value"></output></label>';
 const draw=()=>{const out=+document.getElementById('solute').value;document.getElementById('solute-value').textContent=`${out} relative units`;const points=(n,x)=>Array.from({length:n},(_,i)=>`<circle cx="${x+(i%3)*33}" cy="${75+Math.floor(i/3)*35}" r="8" fill="#bd8663"/>`).join('');drawing.innerHTML=svg(`<rect x="45" y="35" width="510" height="180" rx="18" fill="#e5f0f3"/><path d="M300 35V215" stroke="#547e71" stroke-width="9" stroke-dasharray="16 8"/>${points(4,95)}${points(out,380)}${textSVG(165,250,'Inside: 4 units')}${textSVG(435,250,`Outside: ${out} units`)}${out>4?line(220,180,380,180):out<4?line(380,180,220,180):line(240,180,360,180)}${out===4?line(360,158,240,158):''}`,`Two equal-volume compartments separated by a membrane. Inside solute 4 units; outside ${out}.`);caption.textContent=(out>4?'Net water movement: outward; a model animal cell may shrink.':out<4?'Net water movement: inward; a model animal cell may swell.':'No net water movement from this concentration difference; water still moves both ways.')+' Assumptions: water can cross, solute cannot, and pressure differences are initially negligible. Dots represent solute, not water.';};document.getElementById('solute').oninput=draw;draw();return;
 }
 if(type==='punnett'){
 controls.innerHTML='<label>Parent 1 <select id="p1"><option>Aa</option><option>AA</option><option>aa</option></select></label><label>Parent 2 <select id="p2"><option>Aa</option><option>AA</option><option>aa</option></select></label>';
 const draw=()=>{const a=document.getElementById('p1').value,b=document.getElementById('p2').value,c=[...a].flatMap(x=>[...b].map(y=>[x,y].sort().join('')));drawing.innerHTML=`<div class="punnett-wrap"><table class="punnett"><caption>Each box is one equally likely gamete combination</caption><thead><tr><th scope="col">Gametes</th><th scope="col">${a[0]}</th><th scope="col">${a[1]}</th></tr></thead><tbody>${[...b].map((y,j)=>`<tr><th scope="row">${y}</th>${[...a].map(x=>`<td class="${x==='a'&&y==='a'?'recessive':'dominant'}">${[x,y].sort().join('')}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;const recessive=c.filter(x=>x==='aa').length*25;caption.textContent=`${a} × ${b}: AA ${c.filter(x=>x==='AA').length*25}%, Aa ${c.filter(x=>x==='Aa').length*25}%, aa ${recessive}%. Dominant phenotype ${100-recessive}%; recessive phenotype ${recessive}%. Single-gene, complete-dominance model with equally likely gametes; each offspring is a new probability event.`;};controls.querySelectorAll('select').forEach(s=>s.onchange=draw);draw();return;
 }
 if(type==='dna'){
 controls.innerHTML='<label>DNA template, written 3′ to 5′ <input id="dna-input" value="TACGGA" maxlength="12" spellcheck="false" autocomplete="off"></label><button id="dna-build">Build pairs</button><label>Partner <select id="dna-mode"><option value="dna">DNA complement</option><option value="rna">RNA transcript</option></select></label>';
 const draw=()=>{const seq=document.getElementById('dna-input').value.toUpperCase().replace(/\s/g,''),rna=document.getElementById('dna-mode').value==='rna';if(!/^[ATCG]{1,12}$/.test(seq)){caption.textContent='Enter 1–12 DNA bases using A, T, C, and G.';return;}const pairs={A:rna?'U':'T',T:'A',C:'G',G:'C'},partner=[...seq].map(c=>pairs[c]).join('');drawing.innerHTML=`<div class="dna-strands"><p>Template DNA · 3′ → 5′</p><div class="bases">${[...seq].map(c=>`<span class="base b-${c}">${c}</span>`).join('')}</div><p>${rna?'RNA':'Complementary DNA'} · 5′ → 3′</p><div class="bases">${[...partner].map(c=>`<span class="base b-${c}">${c}</span>`).join('')}</div></div>`;caption.textContent=`Template 3′-${seq}-5′ pairs with ${rna?'RNA':'DNA'} 5′-${partner}-3′. ${rna?'RNA uses U opposite A; transcription makes RNA, not a protein.':'DNA strands run in opposite directions. This ladder model omits the helix and sugar-phosphate backbones.'}`;};document.getElementById('dna-build').onclick=draw;document.getElementById('dna-mode').onchange=draw;draw();return;
 }
 if(type==='selection'){
 let p=.5,g=0;controls.innerHTML='<label>Ground color <select id="ground"><option value="dark">Dark ground favors dark beetles</option><option value="light">Light ground favors light beetles</option><option value="equal">Equal reproductive success</option></select></label><button id="generation">Next generation</button><button class="soft" id="selection-reset">Reset</button>';
 const draw=()=>{const n=Math.round(p*40);drawing.innerHTML=svg(`<rect x="40" y="20" width="520" height="210" rx="20" fill="${document.getElementById('ground').value==='dark'?'#c5b6a4':'#e9e4d1'}"/>${Array.from({length:40},(_,i)=>{const x=70+i%10*50,y=50+Math.floor(i/10)*48;return `<ellipse cx="${x}" cy="${y}" rx="12" ry="16" fill="${i<n?'#4f5047':'#efdc98'}" stroke="#4f5047"/><path d="M${x-14} ${y-8}h28m-28 16h28" stroke="#4f5047"/>`;}).join('')}${textSVG(300,265,`Generation ${g} · expected dark share ${(p*100).toFixed(1)}%`)}`,'Forty beetle symbols approximate the expected proportions of light and dark inherited color types.');caption.textContent='Hypothetical deterministic model: color is inherited; the favored type contributes 1.5 times as many descendants, the other 1.0. Population size is normalized each generation. Symbols are rounded; this model omits drift, mutation, migration, and mating genetics.';};document.getElementById('generation').onclick=()=>{const ground=document.getElementById('ground').value,a=ground==='dark'?1.5:1,b=ground==='light'?1.5:1;p=p*a/(p*a+(1-p)*b);g++;draw();};document.getElementById('ground').onchange=draw;document.getElementById('selection-reset').onclick=()=>{p=.5;g=0;draw();};draw();return;
 }
 if(type==='population'){
 controls.innerHTML='<label>Resource-supported capacity <input id="capacity" type="range" min="30" max="180" value="100" step="10"><output id="capacity-label"></output></label>';
 const draw=()=>{const k=+document.getElementById('capacity').value;document.getElementById('capacity-label').textContent=k;let n=10;const points=[];for(let t=0;t<=30;t++){points.push([50+t*16,235-n]);n+=.3*n*(1-n/k);}drawing.innerHTML=svg(`<path d="M50 30V235H550" stroke="#6c8278" fill="none"/><path d="M50 ${235-k}H550" stroke="#b48052" stroke-dasharray="5 5"/><polyline points="${points.map(p=>p.join(',')).join(' ')}" fill="none" stroke="#3d7761" stroke-width="4"/>${textSVG(300,276,'Time steps')}${textSVG(90,22,'Individuals',15)}${textSVG(40,240,'0',14)}${textSVG(35,137,'100',14)}${textSVG(495,225-k,`Capacity ${k}`,15)}${textSVG(530,254,'30',14)}`,'Logistic population model with population on the vertical axis and time on the horizontal axis.',290);caption.textContent=`Illustrative logistic model: starts at 10 individuals; per-step growth is 0.3 × population × (1 − population/${k}). Change the capacity to compare trajectories. This is not measured wildlife data; real populations also fluctuate and move.`;};document.getElementById('capacity').oninput=draw;draw();return;
 }
 if(type==='web')return buttons([['normal','Show food web'],['loss','What if rabbits decline?']],mode=>{drawing.innerHTML=svg(`${line(140,190,250,65)}${line(150,195,265,190)}${line(350,65,460,65)}${line(350,190,460,85)}${line(340,215,460,245)}${box(30,165,130,65,'Grass')}${box(230,30,135,65,'Rabbits',mode==='loss'?'#efcfbf':'#e4eee5')}${box(230,170,135,65,'Mice')}${box(440,30,130,65,'Foxes')}${box(430,220,150,55,'Owls')}`,'A food web: grass feeds rabbits and mice; rabbits and mice feed foxes; mice feed owls.',310);caption.textContent=mode==='loss'?'Rabbit decline can reduce one food source for foxes. Mice are an alternative, so the final outcome depends on their availability and other interactions. These are possible effects, not an exact prediction.':'Arrows point from food to consumer. This is a simplified example; decomposers and many other connections are omitted. Click the scenario to reason about a change.';});
 if(type==='energy')return buttons([['photo','Photosynthesis'],['resp','Respiration'],['cycle','Carbon connection']],mode=>{const photo=mode==='photo';drawing.innerHTML=mode==='cycle'?svg(`${box(205,20,190,55,'Atmospheric CO₂','#d4e8ed')}${box(30,180,160,65,'Plant biomass')}${box(405,180,160,65,'Consumer biomass','#eadcc6')}${line(220,75,130,177)}${line(190,210,405,210)}${line(480,180,375,75)}${line(105,180,255,75)}${textSVG(105,116,'Photosynthesis',14)}${textSVG(490,120,'Respiration',14)}${textSVG(298,200,'Feeding',14)}`,'Simplified carbon pathways between atmospheric carbon dioxide and plant and consumer biomass.'):svg(`${box(35,95,160,70,photo?'CO₂ + water':'Glucose + O₂','#d8e8e5')}${line(197,130,395,130)}${box(400,95,170,70,photo?'Sugar + O₂':'CO₂ + water','#efe3c8')}${textSVG(300,65,photo?'Light energy enters':'Energy transferred')}${textSVG(300,212,photo?'Chloroplast · photosynthesis':'ATP + heat · respiration')}`,'Summary of '+(photo?'photosynthesis':'aerobic respiration')+' inputs and outputs.');caption.textContent=mode==='cycle'?'Carbon atoms move among reservoirs. This diagram omits soil, oceans, combustion, and other stores. Plants as well as consumers respire.':photo?'Summary: 6CO₂ + 6H₂O + light → C₆H₁₂O₆ + 6O₂. Light supplies energy; atoms are rearranged. The detailed pathway is more complex.':'Summary: C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O. Energy is transferred to ATP and dispersed as heat. Glycolysis is in the cytoplasm; later aerobic stages involve mitochondria in eukaryotes.';});
 if(type==='division')return buttons([['mitosis','Mitosis'],['meiosis','Meiosis']],mode=>{const mei=mode==='meiosis',cells=(cx,cy,n,color)=>`<circle cx="${cx}" cy="${cy}" r="35" fill="${color}" stroke="#658575"/>${Array.from({length:n},(_,i)=>`<path d="M${cx-15+i*10} ${cy-13}v26" stroke="${i%2?'#9d719e':'#426e65'}" stroke-width="5"/>`).join('')}`;drawing.innerHTML=svg(`${cells(300,50,4,'#e6eee1')}${line(280,86,170,140)}${line(320,86,430,140)}${cells(155,180,mei?2:4,'#e8dff0')}${cells(445,180,mei?2:4,'#e8dff0')}${mei?`${line(140,215,95,266)}${line(170,215,215,266)}${line(430,215,385,266)}${line(460,215,505,266)}${[85,225,375,515].map(x=>cells(x,310,2,'#e2ecde')).join('')}`:''}${textSVG(300,mei?374:255,mei?'Four haploid products · 2 chromosomes each':'Two daughter cells · 4 chromosomes each',17)}`,mei?'Overview of a diploid model cell with 4 chromosomes producing four haploid products with 2 each.':'Overview of a cell with 4 chromosomes producing two daughters with 4 each.',mei?405:290);caption.textContent=mei?'Meiosis: DNA is copied once before two divisions. Homologous chromosomes separate first, then sister chromatids. This overview shows chromosome-set counts, not detailed chromatid stages; crossing over is not drawn.':'Mitosis: DNA is copied before division, and duplicated chromosomes are separated so both daughter cells retain the chromosome number. Bars represent chromosome counts in this overview, not all stages of replication.';});
 if(type==='feedback')return buttons([['heat','Temperature rises'],['cold','Temperature falls']],mode=>{const hot=mode==='heat';drawing.innerHTML=svg(`${box(30,20,210,60,hot?'Temperature rises':'Temperature falls','#efe0c6')}${box(350,20,220,60,'Change detected')}${line(240,50,350,50)}${line(465,82,465,175)}${box(320,178,250,65,hot?'Sweating / skin blood flow':'Shivering / less skin flow','#dbe8ec')}${line(320,210,235,210)}${box(25,178,210,65,hot?'Heat loss increases':'Heat retained / produced')}${line(95,178,95,83)}`,'A negative feedback loop connecting a temperature disturbance to responses that counteract it.');caption.textContent=hot?'Negative feedback opposes the temperature rise. Evaporation of sweat can remove heat; effectiveness depends on conditions such as humidity.':'Responses to cooling can include shivering and reduced skin blood flow. These help increase heat production or reduce loss. This is a simplified loop, not a complete account of thermoregulation.';});
 if(type==='systems')return buttons([['lungs','Lungs'],['blood','Circulation'],['muscle','Muscles'],['nerves','Nervous system']],mode=>{drawing.innerHTML=svg(`${box(205,18,190,55,'Lungs',mode==='lungs'?'#bddddc':'#e4eee5')}${box(205,111,190,55,'Blood transport',mode==='blood'?'#e7c4b5':'#e4eee5')}${box(205,204,190,55,'Working muscles',mode==='muscle'?'#ead39c':'#e4eee5')}${line(290,74,290,110)}${line(310,110,310,74)}${line(290,167,290,203)}${line(310,203,310,167)}${box(15,110,160,65,'Nervous signals',mode==='nerves'?'#d7c4e5':'#e4eee5')}${line(174,160,215,218)}${textSVG(485,100,'O₂ delivered',15)}${textSVG(485,135,'CO₂ returned',15)}`,'Lungs exchange gases, blood transports them, and muscles use oxygen for metabolism; nervous signals coordinate activity.');caption.textContent={lungs:'Lungs provide exchange surfaces; oxygen diffuses into blood and carbon dioxide out under typical conditions.',blood:'Circulation connects exchange surfaces with tissues. Gas delivery depends on blood flow and transport capacity.',muscle:'Muscle cells use ATP for contraction and cellular processes to replenish it. Oxygen and fuels support aerobic respiration.',nerves:'Nervous signals coordinate contraction and contribute to regulation. The body’s systems work together rather than independently.'}[mode];});
 if(type==='tree')return buttons([['tree','Read the tree'],['pair','Compare B and C']],mode=>{drawing.innerHTML=svg(`<path d="M80 235V90H230M230 90V38H470M230 90V174H345M345 174V135H470M345 174V225H470" fill="none" stroke="#527b66" stroke-width="4"/><circle cx="230" cy="90" r="7" fill="#ad835c"/><circle cx="345" cy="174" r="${mode==='pair'?12:7}" fill="#ad835c"/>${textSVG(510,44,'Species A')}${textSVG(510,141,'Species B')}${textSVG(510,231,'Species C')}${textSVG(145,275,'Common ancestry',15)}`,'Species B and C share a more recent common ancestor; their lineage joins species A at an older node.',300);caption.textContent=mode==='pair'?'B and C share the highlighted, more recent ancestor. Rotating branches around a node would not change those relationships.':'Read branching connections, not distances between labels. The tree is schematic; branch length here does not represent time or amount of change.';});
 if(type==='enzyme'){
 controls.innerHTML='<label>Model temperature <input id="temperature" type="range" min="0" max="70" value="30"><output id="temperature-value"></output></label>';
 const rate=t=>t<=35?t/35:Math.max(0,1-(t-35)/20),draw=()=>{const t=+document.getElementById('temperature').value,r=rate(t);document.getElementById('temperature-value').textContent=t+' °C';drawing.innerHTML=svg(`<path d="M65 30V225H550" stroke="#678477" fill="none"/><path d="M65 225L300 45L435 225H535" stroke="#578b69" fill="none" stroke-width="4"/><circle cx="${65+t/70*470}" cy="${225-r*180}" r="8" fill="#b8764b"/>${textSVG(310,265,'Temperature (°C)')}${textSVG(100,22,'Relative activity',14)}${textSVG(65,245,'0',14)}${textSVG(300,245,'35',14)}${textSVG(535,245,'70',14)}`,'Hypothetical enzyme activity rises to an optimum and then declines at higher temperature.');caption.textContent=`Model activity: ${Math.round(r*100)}% of its maximum. This deliberately simplified curve has a chosen optimum of 35 °C; it is not measured data or a universal enzyme optimum. Above its working range, loss of structure can reduce activity.`;};document.getElementById('temperature').oninput=draw;draw();return;
 }
 buttons([['graph','Compare growth'],['reason','Explain the evidence']],mode=>{drawing.innerHTML=svg(`<path d="M60 30V225H550" stroke="#678477" fill="none"/>${[0,2,4,6,8].map(n=>`${textSVG(37,230-n*20,String(n),14)}<path d="M60 ${225-n*20}H545" stroke="#dde5db"/>`).join('')}<path d="M60 225L180 185L300 145L420 105L540 65" stroke="#467c60" stroke-width="4" fill="none"/><path d="M60 225L180 215L300 205L420 195L540 185" stroke="#aa7851" stroke-width="4" fill="none" stroke-dasharray="8 5"/>${textSVG(310,275,'Days (0, 1, 2, 3, 4)')}${textSVG(120,20,'Height gained (cm)',14)}${textSVG(410,48,'Light group: 8 cm',16)}${textSVG(410,176,'Dark group: 2 cm',16)}`,'Hypothetical growth data: light group gains 0,2,4,6,8 cm over days 0–4; dark group gains 0,0.5,1,1.5,2 cm.',300);caption.textContent=mode==='reason'?'Claim: the light group grew more under these conditions. Evidence: 8 cm versus 2 cm gained over four days. Reasoning: light supports photosynthesis. Check sample size, variation, and controlled conditions before making a wider causal claim.':'Invented teaching data, not an actual experiment. Solid green: light group; dashed brown: dark group. Light is the treatment; height gained is the measured outcome. What conditions would you keep the same?';});
}
