'use strict';
const svg=(body,label,h=280)=>`<svg viewBox="0 0 600 ${h}" role="img" aria-label="${esc(label)}" xmlns="http://www.w3.org/2000/svg"><defs><marker id="arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0 0L8 4L0 8Z" fill="#446d61"/></marker></defs>${body}</svg>`;
const textSVG=(x,y,t,size=18)=>`<text x="${x}" y="${y}" text-anchor="middle" font-size="${size}" fill="#183d36">${esc(t)}</text>`;
const box=(x,y,w,h,t,fill='#e4eee5')=>`<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="14" fill="${fill}" stroke="#789787"/>${textSVG(x+w/2,y+h/2+6,t)}`;
const line=(x,y,a,b)=>`<path d="M${x} ${y}L${a} ${b}" fill="none" stroke="#446d61" stroke-width="2" marker-end="url(#arrow)"/>`;
const VISUAL_NAMES={experiment:'Read an experiment',enzyme:'Enzyme activity explorer',web:'Explore a food web',population:'Population growth model',energy:'Follow matter and energy',cell:'Explore a living cell',membrane:'Which way will water move?',systems:'A sprint is a team effort',feedback:'Trace a feedback loop',dna:'DNA base-pair builder',division:'Compare cell divisions',punnett:'Build a Punnett square',selection:'Selection over generations',tree:'Read a family tree of life'};
const REAL_LIFE={
 cells:{
  title:"Cells: The Building Blocks of Life",
  intro:"Explore different cells and their amazing parts.",
  slides:[
   {src:'assets/slides/animal-cell.jpg',kicker:"Slide 1",heading:"Animal Cell",body:"A typical animal cell with all the main organelles working together.",labels:"membrane · cytoplasm · nucleus · mitochondria · ER · Golgi · ribosomes"},
   {src:'assets/slides/plant-cell.jpg',kicker:"Slide 2",heading:"Plant Cell",body:"Plant cells have a cell wall, chloroplasts, and a large central vacuole."},
   {src:'assets/slides/human-cells.jpg',kicker:"Slide 3",heading:"Different Human Cells",body:"Same DNA, different shapes and jobs. Cells are specialized for what they do.",labels:"nerve · muscle · white blood cell · red blood cell"},
   {src:'assets/slides/nucleus.jpg',kicker:"Slide 4",heading:"Nucleus",body:"The control center that holds your DNA."},
   {src:'assets/slides/mitochondria.jpg',kicker:"Slide 5",heading:"Mitochondria",body:"Turns food into energy (ATP) for the cell."},
   {src:'assets/slides/er-golgi.jpg',kicker:"Slide 6",heading:"ER and Golgi Apparatus",body:"Rough ER makes proteins. Golgi modifies and packages them.",labels:"rough ER · smooth ER · Golgi · transport vesicles"},
   {src:'assets/slides/ribosome-protein.jpg',kicker:"Slide 7",heading:"Ribosomes",body:"Tiny machines that read instructions and build proteins."}
  ]
 },
 transport:{
  title:"Osmosis in a living cell",
  intro:"This is a microscope view connected to the same water-balance idea shown in the membrane model.",
  exam:"In a hypotonic environment, water tends to enter the cell. Connect what you see to the response that prevents too much water from accumulating.",
  images:[
   {src:"assets/real-life/osmosis-paramecium-micrograph.jpg",alt:"Bright-field microscope image of a Paramecium with a contractile vacuole",label:"Paramecium · bright-field microscope",note:"A contractile vacuole pumps excess water out. It is a real example of a cell managing water that enters by osmosis."}
  ]
 },
 dna:{
  title:"From Cell to DNA to Protein",
  intro:"Follow the incredible journey from a cell to a protein.",
  slides:[
   {src:'assets/slides/animal-cell.jpg',kicker:"Slide 1",heading:"Cell",body:"Everything starts with a cell."},
   {src:'assets/slides/nucleus.jpg',kicker:"Slide 2",heading:"Nucleus",body:"The nucleus holds your DNA."},
   {src:'assets/slides/chromosome.jpg',kicker:"Slide 3",heading:"Chromosome",body:"DNA is tightly coiled into chromosomes."},
   {src:'assets/slides/dna-double-helix.jpg',kicker:"Slide 4",heading:"DNA Double Helix",body:"DNA is a long molecule shaped like a twisted ladder."},
   {src:'assets/slides/gene.jpg',kicker:"Slide 5",heading:"Gene",body:"A gene is a specific segment of DNA with instructions."},
   {src:'assets/slides/dna-letters.jpg',kicker:"Slide 6",heading:"The 4 DNA Letters",body:"DNA uses four chemical letters: A, T, C, and G.",labels:"A pairs with T · C pairs with G"},
   {src:'assets/slides/rna-copy.jpg',kicker:"Slide 7",heading:"RNA Copy (mRNA)",body:"The gene is copied into messenger RNA (mRNA)."},
   {src:'assets/slides/ribosome-protein.jpg',kicker:"Slide 8",heading:"Ribosome",body:"A ribosome reads the mRNA instructions."},
   {src:'assets/slides/amino-acids.jpg',kicker:"Slide 9",heading:"Amino Acids",body:"Amino acids are linked together in the right order."},
   {src:'assets/slides/protein.jpg',kicker:"Slide 10",heading:"Protein",body:"The amino acid chain folds into a protein."},
   {src:'assets/slides/protein-at-work-cell.jpg',kicker:"Slide 11",heading:"Protein at Work: Inside the Cell",body:"Proteins do the work inside the cell."},
   {src:'assets/slides/protein-at-work-membrane.jpg',kicker:"Slide 12",heading:"Protein at Work: At the Membrane",body:"Others work in the cell membrane, controlling what gets in and out."},
   {src:'assets/slides/human-cells.jpg',kicker:"Slide 13",heading:"Same DNA, Different Cells",body:"All your cells have the same DNA, but they use different genes."}
  ]
 },
 mitosis:{
  title:"Mitosis under fluorescence microscopy",
  intro:"The real microscope images in this reference show chromosomes and spindle structures during cell division.",
  exam:"Identify the stage from chromosome position, not from the artificial colors: middle = metaphase; separating = anaphase; two groups at opposite ends = late mitosis.",
  images:[
   {src:"assets/real-life/mitosis-fluorescence.png",alt:"Reference image containing fluorescence micrographs of cells in stages of mitosis",label:"Mitosis · fluorescence microscopy",note:"Blue fluorescence marks DNA/chromosomes and green marks spindle microtubules. The colors come from fluorescent labels used by scientists."}
  ]
 },
 "evolution-evidence":{
  title:"Fossil evidence you can actually see",
  intro:"Fossils are one physical line of evidence scientists combine with anatomy and DNA when reconstructing evolutionary relationships.",
  exam:"A fossil alone does not draw the family tree. Use preserved structures together with homologous anatomy and molecular evidence to support common ancestry.",
  images:[
   {src:"assets/real-life/archaeopteryx-fossil.jpg",alt:"Archaeopteryx reference image including a fossil with preserved skeletal and feather structures",label:"Archaeopteryx · fossil evidence",note:"The fossil portion preserves skeletal and feather features. Fossils let scientists compare structures across organisms and through time."}
  ]
 }
};
/* Two shapes here. `slides` is a paged picture story, one frame at a time,
   for lessons where the point is to follow a sequence. `images` is the older
   side-by-side gallery of real micrographs, still right where the point is
   comparing a clean model against messy real tissue. */
function realLifePanel(lessonId){
 const d=REAL_LIFE[lessonId];if(!d)return '';
 return `<dialog class="real-life-dialog${d.slides?' is-tour':''}" id="real-life-dialog" aria-labelledby="real-life-title"><div class="real-life-shell"><div class="real-life-head"><div><p class="eyebrow">${d.slides?'ILLUSTRATED TOUR':'REAL BIOLOGY'}</p><h2 id="real-life-title">${d.title}</h2></div><div class="real-life-acts">${d.slides?`<span class="ss-count" data-count>1 of ${d.slides.length}</span>`:''}<button type="button" class="soft real-life-close" id="real-life-close" aria-label="Close">Close</button></div></div>${d.slides?'':`<p class="real-life-intro">${d.intro}</p>`}${d.slides?slideshowBody(d):galleryBody(d)}</div></dialog>`;
}
function galleryBody(d){
 return `<div class="real-life-gallery">${d.images.map(x=>`<figure class="real-life-figure"><img src="${x.src}" alt="${x.alt}" loading="lazy"><figcaption><strong>${x.label}</strong><span>${x.note}</span></figcaption></figure>`).join('')}</div><aside class="real-life-exam"><strong>Exam tip</strong><p>${d.exam}</p></aside><p class="small muted real-life-credit">These image files are stored inside Ethan Study Hub. Source and license details are recorded in <code>assets/real-life/SOURCES.md</code>.</p>`;
}
const SS_CHEV='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M9 4.5 16.5 12 9 19.5"/></svg>';
function slideshowBody(d){
 const n=d.slides.length;
 // Picture, then title and words beneath it, the way the catalogue lays
 // its tiles out. Side by side spent half the panel on two lines of text.
 // The slide number lives in the controls, so it is not repeated here.
 const frames=d.slides.map((x,i)=>`<figure class="ss-slide" data-slide="${i}"${i?' hidden':''}><div class="ss-media"${x.todo?'':` style="--shot:url('${x.src}')"`}>${x.todo
   ?`<div class="ss-todo"><strong>Artwork still to come</strong><span>Add the picture as <code>biology/${x.src}</code>, then delete <code>todo:true</code> on this slide.</span></div>`
   :`<img src="${x.src}" alt="${x.heading}" loading="${i?'lazy':'eager'}">`}</div><figcaption class="ss-bot"><h3>${x.heading}</h3><p class="ss-body">${x.body}</p>${x.labels?`<p class="ss-labels">${x.labels.split('·').map(w=>`<span class="ss-chip">${w.trim()}</span>`).join('')}</p>`:''}</figcaption></figure>`).join('');
 const dots=d.slides.map((x,i)=>`<button type="button" class="ss-dot${i?'':' is-on'}" data-go="${i}" aria-label="Go to slide ${i+1}"></button>`).join('');
 return `<div class="ss" data-slideshow><div class="ss-stage">${frames}</div><div class="ss-controls"><button type="button" class="ss-arrow ss-arrow--prev" data-step="-1" aria-label="Previous slide">${SS_CHEV}</button><div class="ss-dots">${dots}</div><button type="button" class="ss-arrow ss-arrow--next" data-step="1" aria-label="Next slide">${SS_CHEV}</button></div></div>`;
}
function bindRealLife(lessonId){
 const dialog=document.getElementById('real-life-dialog'),open=document.getElementById('real-life-open');if(!dialog||!open||!REAL_LIFE[lessonId])return;
 const close=document.getElementById('real-life-close');
 const shut=()=>{if(typeof dialog.close==='function')dialog.close();else dialog.removeAttribute('open');};
 open.onclick=()=>{if(typeof dialog.showModal==='function')dialog.showModal();else dialog.setAttribute('open','');};
 close.onclick=shut;
 dialog.addEventListener('click',e=>{if(e.target===dialog)shut();});

 const ss=dialog.querySelector('[data-slideshow]');if(!ss)return;
 const slides=[...ss.querySelectorAll('[data-slide]')],dots=[...ss.querySelectorAll('[data-go]')],count=dialog.querySelector('[data-count]');
 let at=0;
 const show=i=>{at=(i+slides.length)%slides.length;
  slides.forEach((f,n)=>{f.hidden=n!==at;});
  dots.forEach((b,n)=>b.classList.toggle('is-on',n===at));
  count.textContent=`${at+1} of ${slides.length}`;};
 ss.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>show(at+Number(b.dataset.step)));
 dots.forEach(b=>b.onclick=()=>show(Number(b.dataset.go)));
 // Arrow keys page the story without hunting for the button.
 dialog.addEventListener('keydown',e=>{
  if(e.key==='ArrowRight'){e.preventDefault();show(at+1);}
  if(e.key==='ArrowLeft'){e.preventDefault();show(at-1);}});
}
function visualPanel(type,lessonId){const real=REAL_LIFE[lessonId];return `<section class="visual card"><div class="section-top"><div><p class="eyebrow">SEE IT · CHANGE IT · EXPLAIN IT</p><h2>${VISUAL_NAMES[type]}</h2></div><div class="visual-head-actions"><span class="tag">Interactive</span>${real?`<button type="button" class="soft real-life-trigger" id="real-life-open" title="Compare this diagram with real biology">📷 ${real.slides?'Picture tour':'Real image'}</button>`:''}</div></div><div id="visual-controls" class="controls"></div><div id="visual-drawing" class="drawing"></div><p id="visual-caption" class="visual-caption" role="status" aria-live="polite"></p><p class="small muted">Simplified learning model. Read the explanation and assumptions below the image.</p></section>${realLifePanel(lessonId)}`;}
function mountVisual(type,lessonId){
 const controls=document.getElementById('visual-controls'),drawing=document.getElementById('visual-drawing'),caption=document.getElementById('visual-caption');if(!controls)return;bindRealLife(lessonId);
 const buttons=(items,fn)=>{controls.innerHTML=items.map(([value,label])=>`<button class="soft" data-value="${value}">${label}</button>`).join('');controls.querySelectorAll('button').forEach(b=>b.onclick=()=>{controls.querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));fn(b.dataset.value);});controls.querySelector('button').click();};
 if(type==='cell'){
 let plant=false,part='nucleus';const descriptions={nucleus:'Nucleus: contains most DNA in a eukaryotic cell and is a site of transcription.',mitochondrion:'Mitochondrion: participates in aerobic respiration. Both plant and animal cells have mitochondria.',membrane:'Cell membrane: selectively regulates exchange. Plant cells also have a wall outside the membrane.',ribosome:'Ribosomes: assemble proteins. They occur in plant, animal, and prokaryotic cells.',chloroplast:'Chloroplast: uses light in photosynthesis. This is a typical photosynthetic plant cell; not all plant cells contain chloroplasts.',vacuole:'Large central vacuole: stores material and helps support a plant cell through water pressure.'};
 controls.innerHTML='<label>Cell type <select id="cell-type"><option value="animal">Animal cell</option><option value="plant">Photosynthetic plant cell</option></select></label><div id="cell-parts" class="controls"></div>';
 const draw=()=>{const parts=['nucleus','mitochondrion','membrane','ribosome',...(plant?['chloroplast','vacuole']:[])];if(!parts.includes(part))part='nucleus';document.getElementById('cell-parts').innerHTML=parts.map(p=>`<button class="soft" data-part="${p}" aria-pressed="${part===p}">${p[0].toUpperCase()+p.slice(1)}</button>`).join('');const highlight=p=>part===p?'stroke="#173f35" stroke-width="5"':'stroke="#6a9181" stroke-width="2"';drawing.innerHTML=svg(`${plant?'<rect x="95" y="15" width="410" height="255" rx="35" fill="#acc493" stroke="#5d794d" stroke-width="8"/>':''}<rect x="${plant?105:110}" y="25" width="${plant?390:380}" height="235" rx="${plant?30:115}" fill="#e3eee1" ${highlight('membrane')}/>${plant?`<rect x="260" y="63" width="195" height="155" rx="25" fill="#c8e1e9" ${highlight('vacuole')}/>`:''}<ellipse cx="230" cy="133" rx="56" ry="48" fill="#d1c0df" ${highlight('nucleus')}/><circle cx="227" cy="132" r="17" fill="#9c85af"/><ellipse cx="340" cy="220" rx="38" ry="17" fill="#efc598" ${highlight('mitochondrion')}/><path d="M310 220l10-8 10 16 10-16 10 16 10-8" stroke="#aa7445" fill="none"/>${[ [155,100],[168,173],[295,70],[394,45],[285,235] ].map(([x,y])=>`<circle cx="${x}" cy="${y}" r="5" fill="#735f7e" ${part==='ribosome'?'stroke="#183d36" stroke-width="3"':''}/>`).join('')}${plant?`<ellipse cx="170" cy="220" rx="35" ry="14" fill="#8ab983" ${highlight('chloroplast')}/><path d="M148 214h44m-44 6h44m-44 6h44" stroke="#3c7750"/>`:''}${textSVG(300,295,plant?'Plant cell schematic':'Animal cell schematic')}`, 'Schematic cell. Select a named structure to highlight it and read its role.',320);caption.textContent=descriptions[part]+' Other structures are omitted; shapes and sizes are simplified.';document.querySelectorAll('[data-part]').forEach(b=>b.onclick=()=>{part=b.dataset.part;draw();});};document.getElementById('cell-type').onchange=e=>{plant=e.target.value==='plant';draw();};draw();return;
 }
 if(type==='membrane'){
 controls.innerHTML='<label>Outside solute concentration <input type="range" id="solute" min="0" max="10" value="8"><output id="solute-value"></output></label>';
 const draw=()=>{const out=+document.getElementById('solute').value;document.getElementById('solute-value').textContent=`${out} relative units`;const points=(n,x)=>Array.from({length:n},(_,i)=>`<circle cx="${x+(i%3)*33}" cy="${75+Math.floor(i/3)*35}" r="8" fill="#bd8663"/>`).join('');drawing.innerHTML=svg(`<rect x="45" y="35" width="510" height="180" rx="18" fill="#e5f0f3"/><path d="M300 35V215" stroke="#547e71" stroke-width="9" stroke-dasharray="16 8"/>${points(4,95)}${points(out,380)}${textSVG(165,250,'Inside: 4 units')}${textSVG(435,250,`Outside: ${out} units`)}${out>4?line(220,180,380,180):out<4?line(380,180,220,180):line(240,180,360,180)}${out===4?line(360,158,240,158):''}`,`Two equal-volume compartments separated by a membrane. Inside solute 4 units; outside ${out}.`);caption.textContent=(out>4?'Net water movement: outward; a model animal cell may shrink.':out<4?'Net water movement: inward; a model animal cell may swell.':'No net water movement from this concentration difference; water still moves both ways.')+' Assumptions: water can cross, solute cannot, and pressure differences are initially negligible. Dots represent solute, not water.';};document.getElementById('solute').oninput=draw;draw();return;
 }
 if(type==='punnett'){
 controls.innerHTML='<label>Parent 1 <select id="p1"><option>Aa</option><option>AA</option><option>aa</option></select></label><label>Parent 2 <select id="p2"><option>Aa</option><option>AA</option><option>aa</option></select></label>';
 const draw=()=>{const a=document.getElementById('p1').value,b=document.getElementById('p2').value,c=[...a].flatMap(x=>[...b].map(y=>[x,y].sort().join('')));drawing.innerHTML=`<div class="punnett-wrap"><table class="punnett"><caption>Each box is one equally likely gamete combination</caption><thead><tr><th scope="col">Gametes</th><th scope="col">${a[0]}</th><th scope="col">${a[1]}</th></tr></thead><tbody>${[...b].map((y,j)=>`<tr><th scope="row">${y}</th>${[...a].map(x=>`<td class="${x==='a'&&y==='a'?'recessive':'dominant'}">${[x,y].sort().join('')}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;const recessive=c.filter(x=>x==='aa').length*25;caption.textContent=`${a} × ${b}: AA ${c.filter(x=>x==='AA').length*25}%, Aa ${c.filter(x=>x==='Aa').length*25}%, aa ${recessive}%. Dominant phenotype ${100-recessive}%; recessive phenotype ${recessive}%. Single-gene, complete-dominance model with equally likely gametes; each offspring is a new probability event.`;};controls.querySelectorAll('select').forEach(s=>s.onchange=draw);draw();return;
 }
 if(type==='dna'){
 controls.innerHTML='<label>DNA template, written 3′ to 5′ <input id="dna-input" value="TACGGA" maxlength="12" spellcheck="false" autocomplete="off"></label><button id="dna-build">Build pairs</button><label>Partner <select id="dna-mode"><option value="dna">DNA complement</option><option value="rna">RNA transcript</option></select></label>';
 const draw=()=>{const seq=document.getElementById('dna-input').value.toUpperCase().replace(/\s/g,''),rna=document.getElementById('dna-mode').value==='rna';if(!/^[ATCG]{1,12}$/.test(seq)){caption.textContent='Enter 1–12 DNA bases using A, T, C, and G.';return;}const pairs={A:rna?'U':'T',T:'A',C:'G',G:'C'},partner=[...seq].map(c=>pairs[c]).join('');drawing.innerHTML=`<div class="dna-strands"><p>Template DNA · 3′ → 5′</p><div class="bases">${[...seq].map(c=>`<span class="base b-${c}">${c}</span>`).join('')}</div><p>${rna?'RNA':'Complementary DNA'} · 5′ → 3′</p><div class="bases">${[...partner].map(c=>`<span class="base b-${c}">${c}</span>`).join('')}</div></div>`;caption.textContent=`Template 3′-${seq}-5′ pairs with ${rna?'RNA':'DNA'} 5′-${partner}-3′. ${rna?'RNA uses U opposite A; transcription makes RNA, not a protein.':'DNA strands run in opposite directions. This ladder model omits the helix and sugar-phosphate backbones.'}`;};document.getElementById('dna-build').onclick=draw;document.getElementById('dna-mode').onchange=draw;draw();return;
 }
 if(type==='selection'){
 let p=.5,g=0;controls.innerHTML='<label>Ground color <select id="ground"><option value="dark">Dark ground favors dark beetles</option><option value="light">Light ground favors light beetles</option><option value="equal">Equal reproductive success</option></select></label><button id="generation">Next generation</button><button class="soft" id="selection-reset">Reset</button>';
 const draw=()=>{const n=Math.round(p*40);drawing.innerHTML=svg(`<rect x="40" y="20" width="520" height="210" rx="20" fill="${document.getElementById('ground').value==='dark'?'#c5b6a4':'#e9e4d1'}"/>${Array.from({length:40},(_,i)=>{const x=70+i%10*50,y=50+Math.floor(i/10)*48;return `<ellipse cx="${x}" cy="${y}" rx="12" ry="16" fill="${i<n?'#4f5047':'#efdc98'}" stroke="#4f5047"/><path d="M${x-14} ${y-8}h28m-28 16h28" stroke="#4f5047"/>`;}).join('')}${textSVG(300,265,`Generation ${g} · expected dark share ${(p*100).toFixed(1)}%`)}`,'Forty beetle symbols approximate the expected proportions of light and dark inherited color types.');caption.textContent='Hypothetical deterministic model: color is inherited; the favored type contributes 1.5 times as many descendants, the other 1.0. Population size is normalized each generation. Symbols are rounded; this model omits drift, mutation, migration, and mating genetics.';};document.getElementById('generation').onclick=()=>{const ground=document.getElementById('ground').value,a=ground==='dark'?1.5:1,b=ground==='light'?1.5:1;p=p*a/(p*a+(1-p)*b);g++;draw();};document.getElementById('ground').onchange=draw;document.getElementById('selection-reset').onclick=()=>{p=.5;g=0;draw();};draw();return;
 }
 if(type==='population'){
 controls.innerHTML='<label>Resource-supported capacity <input id="capacity" type="range" min="30" max="180" value="100" step="10"><output id="capacity-label"></output></label>';
 const draw=()=>{const k=+document.getElementById('capacity').value;document.getElementById('capacity-label').textContent=k;let n=10;const points=[];for(let t=0;t<=30;t++){points.push([50+t*16,235-n]);n+=.3*n*(1-n/k);}drawing.innerHTML=svg(`<path d="M50 30V235H550" stroke="#6c8278" fill="none"/><path d="M50 ${235-k}H550" stroke="#b48052" stroke-dasharray="5 5"/><polyline points="${points.map(p=>p.join(',')).join(' ')}" fill="none" stroke="#3d7761" stroke-width="4"/>${textSVG(300,276,'Time steps')}${textSVG(90,22,'Individuals',15)}${textSVG(40,240,'0',14)}${textSVG(35,137,'100',14)}${textSVG(495,225-k,`Capacity ${k}`,15)}${textSVG(530,254,'30',14)}`,'Logistic population model with population on the vertical axis and time on the horizontal axis.',290);caption.textContent=`Illustrative logistic model: starts at 10 individuals; per-step growth is 0.3 × population × (1 − population/${k}). Change the capacity to compare trajectories. This is not measured wildlife data; real populations also fluctuate and move.`;};document.getElementById('capacity').oninput=draw;draw();return;
 }
 if(type==='web')return buttons([['normal','Show food web'],['loss','What if rabbits decline?']],mode=>{drawing.innerHTML=svg(`${line(140,190,250,65)}${line(150,195,265,190)}${line(350,65,460,65)}${line(350,190,460,85)}${line(340,215,460,245)}${box(30,165,130,65,'Grass')}${box(230,30,135,65,'Rabbits',mode==='loss'?'#efcfbf':'#e4eee5')}${box(230,170,135,65,'Mice')}${box(440,30,130,65,'Foxes')}${box(430,220,150,55,'Owls')}`,'A food web: grass feeds rabbits and mice; rabbits and mice feed foxes; mice feed owls.',310);caption.textContent=mode==='loss'?'Rabbit decline can reduce one food source for foxes. Mice are an alternative, so the final outcome depends on their availability and other interactions. These are possible effects, not an exact prediction.':'Arrows point from food to consumer. This is a simplified example; decomposers and many other connections are omitted. Click the scenario to reason about a change.';});
 if(type==='energy')return buttons([['photo','Photosynthesis'],['resp','Respiration'],['cycle','Carbon connection']],mode=>{const photo=mode==='photo';drawing.innerHTML=mode==='cycle'?svg(`${box(205,20,190,55,'Atmospheric CO₂','#d4e8ed')}${box(30,180,160,65,'Plant biomass')}${box(405,180,160,65,'Consumer biomass','#eadcc6')}${line(220,75,130,177)}${line(190,210,405,210)}${line(480,180,375,75)}${line(105,180,255,75)}${textSVG(105,116,'Photosynthesis',14)}${textSVG(490,120,'Respiration',14)}${textSVG(298,200,'Feeding',14)}`,'Simplified carbon pathways between atmospheric carbon dioxide and plant and consumer biomass.'):svg(`${box(35,95,160,70,photo?'CO₂ + water':'Glucose + O₂','#d8e8e5')}${line(197,130,395,130)}${box(400,95,170,70,photo?'Sugar + O₂':'CO₂ + water','#efe3c8')}${textSVG(300,65,photo?'Light energy enters':'Energy transferred')}${textSVG(300,212,photo?'Chloroplast · photosynthesis':'ATP + heat · respiration')}`,'Summary of '+(photo?'photosynthesis':'aerobic respiration')+' inputs and outputs.');caption.textContent=mode==='cycle'?'Carbon atoms move among reservoirs. This diagram omits soil, oceans, combustion, and other stores. Plants as well as consumers respire.':photo?'Summary: 6CO₂ + 6H₂O + light → C₆H₁₂O₆ + 6O₂. Light supplies energy; atoms are rearranged. The detailed pathway is more complex.':'Summary: C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O. Energy is transferred to ATP and dispersed as heat. Glycolysis is in the cytoplasm; later aerobic stages involve mitochondria in eukaryotes.';});
 if(type==='division')return buttons([['mitosis','Mitosis'],['meiosis','Meiosis']],mode=>{const mei=mode==='meiosis',cells=(cx,cy,n,color)=>`<circle cx="${cx}" cy="${cy}" r="35" fill="${color}" stroke="#658575"/>${Array.from({length:n},(_,i)=>`<path d="M${cx-15+i*10} ${cy-13}v26" stroke="${i%2?'#9d719e':'#426e65'}" stroke-width="5"/>`).join('')}`;drawing.innerHTML=svg(`${cells(300,50,4,'#e6eee1')}${line(280,86,170,140)}${line(320,86,430,140)}${cells(155,180,mei?2:4,'#e8dff0')}${cells(445,180,mei?2:4,'#e8dff0')}${mei?`${line(140,215,95,266)}${line(170,215,215,266)}${line(430,215,385,266)}${line(460,215,505,266)}${[85,225,375,515].map(x=>cells(x,310,2,'#e2ecde')).join('')}`:''}${textSVG(300,mei?374:255,mei?'Four haploid products · 2 chromosomes each':'Two daughter cells · 4 chromosomes each',17)}`,mei?'Overview of a diploid model cell with 4 chromosomes producing four haploid products with 2 each.':'Overview of a cell with 4 chromosomes producing two daughters with 4 each.',mei?405:290);caption.textContent=mei?'Meiosis: DNA is copied once before two divisions. Homologous chromosomes separate first, then sister chromatids. This overview shows chromosome-set counts, not detailed chromatid stages; crossing over is not drawn.':'Mitosis: DNA is copied before division, and duplicated chromosomes are separated so both daughter cells retain the chromosome number. Bars represent chromosome counts in this overview, not all stages of replication.';});
 if(type==='feedback')return buttons([['heat','Temperature rises'],['cold','Temperature falls']],mode=>{const hot=mode==='heat';drawing.innerHTML=svg(`${box(30,20,210,60,hot?'Temperature rises':'Temperature falls','#efe0c6')}${box(350,20,220,60,'Change detected')}${line(240,50,350,50)}${line(465,82,465,175)}${box(320,178,250,65,hot?'Sweating / skin blood flow':'Shivering / less skin flow','#dbe8ec')}${line(320,210,235,210)}${box(25,178,210,65,hot?'Heat loss increases':'Heat retained / produced')}${line(95,178,95,83)}`,'A negative feedback loop connecting a temperature disturbance to responses that counteract it.');caption.textContent=hot?'Negative feedback opposes the temperature rise. Evaporation of sweat can remove heat; effectiveness depends on conditions such as humidity.':'Responses to cooling can include shivering and reduced skin blood flow. These help increase heat production or reduce loss. This is a simplified loop, not a complete account of thermoregulation.';});
 if(type==='systems')return buttons([['lungs','Lungs'],['blood','Circulation'],['muscle','Muscles'],['nerves','Nervous system']],mode=>{drawing.innerHTML=svg(`${box(205,18,190,55,'Lungs',mode==='lungs'?'#bddddc':'#e4eee5')}${box(205,111,190,55,'Blood transport',mode==='blood'?'#e7c4b5':'#e4eee5')}${box(205,204,190,55,'Working muscles',mode==='muscle'?'#ead39c':'#e4eee5')}${line(290,74,290,110)}${line(310,110,310,74)}${line(290,167,290,203)}${line(310,203,310,167)}${box(15,110,160,65,'Nervous signals',mode==='nerves'?'#d7c4e5':'#e4eee5')}${line(174,160,215,218)}${textSVG(485,100,'O₂ delivered',15)}${textSVG(485,135,'CO₂ returned',15)}`,'Lungs exchange gases, blood transports them, and muscles use oxygen for metabolism; nervous signals coordinate activity.');caption.textContent={lungs:'Lungs provide exchange surfaces; oxygen diffuses into blood and carbon dioxide out under typical conditions.',blood:'Circulation connects exchange surfaces with tissues. Gas delivery depends on blood flow and transport capacity.',muscle:'Muscle cells use ATP for contraction and cellular processes to replenish it. Oxygen and fuels support aerobic respiration.',nerves:'Nervous signals coordinate contraction and contribute to regulation. The body’s systems work together rather than independently.'}[mode];});
 if(type==='tree')return buttons([['tree','Read the tree'],['pair','Compare B and C']],mode=>{drawing.innerHTML=svg(`<path d="M80 235V90H230M230 90V38H470M230 90V174H345M345 174V135H470M345 174V225H470" fill="none" stroke="#527b66" stroke-width="4"/><circle cx="230" cy="90" r="7" fill="#ad835c"/><circle cx="345" cy="174" r="${mode==='pair'?12:7}" fill="#ad835c"/>${textSVG(510,44,'Species A')}${textSVG(510,141,'Species B')}${textSVG(510,231,'Species C')}${textSVG(145,275,'Common ancestry',15)}`,'Species B and C share a more recent common ancestor; their lineage joins species A at an older node.',300);caption.textContent=mode==='pair'?'B and C share the highlighted, more recent ancestor. Rotating branches around a node would not change those relationships.':'Read branching connections, not distances between labels. The tree is schematic; branch length here does not represent time or amount of change.';});
 if(type==='enzyme'){
 controls.innerHTML='<label>Model temperature <input id="temperature" type="range" min="0" max="70" value="30"><output id="temperature-value"></output></label>';
 const rate=t=>t<=35?t/35:Math.max(0,1-(t-35)/20),draw=()=>{const t=+document.getElementById('temperature').value,r=rate(t);document.getElementById('temperature-value').textContent=t+' °C';drawing.innerHTML=svg(`<path d="M65 30V225H550" stroke="#678477" fill="none"/><path d="M65 225L300 45L435 225H535" stroke="#578b69" fill="none" stroke-width="4"/><circle cx="${65+t/70*470}" cy="${225-r*180}" r="8" fill="#b8764b"/>${textSVG(310,265,'Temperature (°C)')}${textSVG(100,22,'Relative activity',14)}${textSVG(65,245,'0',14)}${textSVG(300,245,'35',14)}${textSVG(535,245,'70',14)}`,'Hypothetical enzyme activity rises to an optimum and then declines at higher temperature.');caption.textContent=`Model activity: ${Math.round(r*100)}% of its maximum. This deliberately simplified curve has a chosen optimum of 35 °C; it is not measured data or a universal enzyme optimum. Above its working range, loss of structure can reduce activity.`;};document.getElementById('temperature').oninput=draw;draw();return;
 }
 buttons([['graph','Compare growth'],['reason','Explain the evidence']],mode=>{drawing.innerHTML=svg(`<path d="M60 30V225H550" stroke="#678477" fill="none"/>${[0,2,4,6,8].map(n=>`${textSVG(37,230-n*20,String(n),14)}<path d="M60 ${225-n*20}H545" stroke="#dde5db"/>`).join('')}<path d="M60 225L180 185L300 145L420 105L540 65" stroke="#467c60" stroke-width="4" fill="none"/><path d="M60 225L180 215L300 205L420 195L540 185" stroke="#aa7851" stroke-width="4" fill="none" stroke-dasharray="8 5"/>${textSVG(310,275,'Days (0, 1, 2, 3, 4)')}${textSVG(120,20,'Height gained (cm)',14)}${textSVG(410,48,'Light group: 8 cm',16)}${textSVG(410,176,'Dark group: 2 cm',16)}`,'Hypothetical growth data: light group gains 0,2,4,6,8 cm over days 0–4; dark group gains 0,0.5,1,1.5,2 cm.',300);caption.textContent=mode==='reason'?'Claim: the light group grew more under these conditions. Evidence: 8 cm versus 2 cm gained over four days. Reasoning: light supports photosynthesis. Check sample size, variation, and controlled conditions before making a wider causal claim.':'Invented teaching data, not an actual experiment. Solid green: light group; dashed brown: dark group. Light is the treatment; height gained is the measured outcome. What conditions would you keep the same?';});
}
